wp-content/themes/sme-portal-institucional/classes/Usuarios/CamposAdicionais.php
wp-content/themes/sme-portal-institucional/classes/Usuarios/Colaborador/Colaborador.php
wp-content/themes/sme-portal-institucional/classes/Usuarios/EnviarParaRevisao.php
wp-content/themes/sme-portal-institucional/classes/init.php
wp-content/themes/tema-dres/classes/ModelosDePaginas/PaginaInicial/PaginaInicialAgenda.php
wp-content/themes/tema-dres/classes/TemplateHierarchy/ArchiveAgenda/ArchiveAgendaGetDatasEventos.php
wp-content/themes/tema-dres/classes/Usuarios/Dre/Dre.php
wp-content/themes/tema-dres/functions.php
wp-content/themes/tema-dres/header.php
wp-content/themes/tema-dres/style.css

Resolvendo pendencias das páginas: No wp-admin, as páginas visitadas como colaborador estavam ficando pendentes mesmo sem serem feitas qualquer alteração ou ser enviada para revisão.

Resolvendo pendencias de usuarios das paginas

---

wp-content/themes/tema-dres/classes/ModelosDePaginas/PaginaInicial/PaginaInicialEndereco.php
wp-content/themes/tema-dres/classes/ModelosDePaginas/PaginaInicial/PaginaInicialEscolares.php
wp-content/themes/tema-dres/classes/TemplateHierarchy/ArchiveAgenda/ArchiveAgendaAjaxCalendario.php
wp-content/themes/tema-dres/classes/assets/css/pagina-inicial.css
wp-content/themes/tema-dres/js/scripts.js
wp-content/themes/tema-dres/search.php
wp-content/themes/tema-dres/style.css

CARD 9534 [Portal SME] DRE - Implementar as páginas iniciais de cada umas das 13 DREs
Foi realizado os ajustes para os criterios de acessibilidade, pagina de busca, a ajustes no layout da Home das DREs

CARD9534 Programando acessibilidade, busca e ajuste de layout da Home

---

wp-content/themes/sme-portal-institucional/style.css

Remover cinza do fundo das personas na Home

Remover cinza do fundo das personas

---

wp-content/themes/tema-dres/style.css

programando Mobile da home das DREs, esse arquivo é um complemento do Card 9534

Programando Mobile Home DRE complemento do Card 9534

---

wp-content/themes/tema-dres/classes/TemplateHierarchy/ArchiveAgenda/ArchiveAgenda.php
wp-content/themes/tema-dres/classes/assets/css/agenda-dre.css
wp-content/themes/tema-dres/classes/assets/js/ajax-agenda-dre.js

Ajustando layout para versão mobile da página mais eventos das DREs

CARD10629 Ajustando mobile pagina mais eventos das DREs

---

wp-content/themes/sme-portal-institucional/classes/assets/css/pagina-inicial.css
wp-content/themes/tema-dres/classes/Cpt/CptPosts.php
wp-content/themes/tema-dres/classes/ModelosDePaginas/PaginaMaisNoticias/PaginaMaisNoticias.php
wp-content/themes/tema-dres/classes/ModelosDePaginas/PaginaMaisNoticias/PaginaMaisNoticiasDestaques.php
wp-content/themes/tema-dres/classes/ModelosDePaginas/PaginaMaisNoticias/PaginaMaisNoticiasMaisLidas.php
wp-content/themes/tema-dres/classes/TemplateHierarchy/ArchiveAgenda/ArchiveAgenda.php
wp-content/themes/tema-dres/functions.php
wp-content/themes/tema-dres/search.php
wp-content/themes/tema-dres/style.css

Programando pagina mais noticias das DREs e Criando paginação

CARD10634 Programando pagina mais noticias e paginacao

---

wp-content/themes/tema-conselhos/classes/LoadDependences.php
wp-content/themes/tema-conselhos/classes/ModelosDePaginas/AgendaConselho/PaginaAgendaConselho.php
wp-content/themes/tema-conselhos/classes/assets/css/pagina-agenda-conselho.css

Criação do loop de conteudo da Agenda, configuração no admin e paginação

Loop de conteudo da agenda e Paginação

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/PaginaMaisNoticias/PaginaMaisNoticiasDestaques.php
wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/PaginaMaisNoticias/PaginaMaisNoticiasOutrasNoticias.php
wp-content/themes/sme-portal-institucional/classes/assets/css/pagina-mais-noticias.css

- Continuando melhorias nas notícias

Continuando melhorias nas notícias

---

wp-content/themes/sme-portal-institucional/classes/Lib/Util.php

Foi criado campo de controle no admin e condições no código

criado campos e condições no admin e no código

---

wp-content/themes/sme-portal-institucional/classes/Lib/Util.php
wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/PaginaInicial/PaginaInicial.php

Modificando titulo e botão da home

Troca de tirulo e botao na home

---

wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/LoopSingle/LoopSingleRelacionadas.php
wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/sme-portal-institucional/style.css

Criando paginação de posts relacionados e modificando a query padrão para exibir na URL

Criando paginação em noticias relacionadas

---

wp-content/themes/sme-portal-institucional/classes/Lib/Util.php
wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/PaginaInicial/PaginaInicialNoticiasDestaquePrimaria.php
wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/PaginaInicial/PaginaInicialNoticiasDestaqueSecundarias.php
wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/PaginaMaisNoticias/PaginaMaisNoticiasDestaques.php
wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/PaginaMaisNoticias/PaginaMaisNoticiasOutrasNoticias.php
wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/LoopSingle/LoopSingleNoticiaPrincipal.php
wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/LoopSingle/LoopSingleRelacionadas.php
wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/sme-portal-institucional/search.php
wp-content/themes/tema-conselhos/classes/Usuarios/Administrador/Administrador.php
wp-content/themes/tema-conselhos/classes/Usuarios/Editor/Editor.php

Foi adicionado uma condição para todos os loops do portal para trazer o subtitulo das materias migradas do antigo portal

incluindo condição para subtitulos de postagens antes da migração

---

wp-content/themes/sme-portal-institucional/classes/LoadDependences.php
wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/LandingPages/Modelo_1.php
wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/sme-portal-institucional/index.php
wp-content/themes/sme-portal-institucional/search.php
wp-content/themes/sme-portal-institucional/style.css
wp-content/themes/tema-conselhos/search.php
wp-content/themes/tema-conselhos/style.css
wp-content/themes/tema-dres/search.php
wp-content/themes/tema-dres/style.css

Programando Busca para trazer resultados ordenados de todos os sites conforme a ordem de relevância e paginação

Programando busca geral multsites

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/PaginaInicial/PaginaInicial.php
wp-content/themes/sme-portal-institucional/classes/assets/css/pagina-inicial.css

Criando modal pop up para o portal, para avisos na home

Criar modal para aviso na home do portal

---

wp-content/themes/sme-portal-institucional/classes/LoadDependences.php
wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/LandingPages/Modelo_2.php
wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/PaginaMaisNoticias/PaginaMaisNoticiasOutrasNoticias.php
wp-content/themes/sme-portal-institucional/classes/assets/css/lp-modelo-2.css
wp-content/themes/sme-portal-institucional/classes/assets/css/pagina-mais-noticias.css
wp-content/themes/sme-portal-institucional/classes/init.php
wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/sme-portal-institucional/pagina-modelo-2.php

Foi desenvolvido um modelo pagina para LandPage 2 com 3 blocos que podem ser reutilizados futuramente para outros assuntos.

Criando modelo de landpage com 3 blocos

---

wp-content/themes/sme-portal-institucional/header.php
wp-content/themes/sme-portal-institucional/search.php
wp-content/themes/sme-portal-institucional/style.css

Criando filtros para busca avançada do portal e sites

Criando filtros para busca avançada

---

wp-content/themes/sme-portal-institucional/classes/assets/css/pagina-inicial.css

Foi comentado o css que não é mais necessário para abas

foi substituido o css para abas

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/PaginaInicial/PaginaInicial.php
wp-content/themes/sme-portal-institucional/classes/assets/css/pagina-inicial.css

Criando admin para criação e ativação do modal na home

Criando admin para criação de modal

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/PaginaInicial/PaginaInicialNoticiasDestaquePrimaria.php
wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/PaginaMaisNoticias/PaginaMaisNoticiasDestaques.php
wp-content/themes/sme-portal-institucional/classes/assets/css/pagina-inicial.css
wp-content/themes/sme-portal-institucional/classes/assets/css/pagina-mais-noticias.css

Foi programado e criado CSS para controlar versões da faixa desktop e mobile

Adicionado CSS para controlar versoes da faixa para desktop e mobile

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/LandingPages/Modelo_2.php
wp-content/themes/sme-portal-institucional/classes/assets/css/pagina-inicial.css
wp-content/themes/sme-portal-institucional/search.php
wp-content/themes/sme-portal-institucional/style.css
wp-content/themes/tema-dres/classes/TemplateHierarchy/ArchiveAgenda/ArchiveAgenda.php

Foi criado uma pagina com 2 campos de busca para pagina da agenda da DRE , sendo um para termo e outro para data.

Programando busca para agenda da DRE

---

wp-content/themes/sme-portal-institucional/classes/LoadDependences.php
wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-portal-institucional/classes/Usuarios/Colaborador/Colaborador.php
wp-content/themes/sme-portal-institucional/classes/assets/css/construtor.css
wp-content/themes/sme-portal-institucional/classes/assets/css/lp-modelo-1.css
wp-content/themes/sme-portal-institucional/classes/assets/css/lp-modelo-2.css
wp-content/themes/sme-portal-institucional/classes/init.php
wp-content/themes/sme-portal-institucional/construtor-layout.php
wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/sme-portal-institucional/search2.php
wp-content/themes/tema-conselhos/classes/ModelosDePaginas/AgendaConselho/PaginaAgendaConselho.php
wp-content/themes/tema-conselhos/classes/ModelosDePaginas/PaginaCards/PaginaCards.php
wp-content/themes/tema-conselhos/functions.php

Criação do template flexível e dinâmico para criação de páginas dentro do portal

Criação do template flexivel para criação de páginas dentro do portal

---

wp-content/themes/sme-portal-institucional/classes/Usuarios/Colaborador/Colaborador.php

Foi adicionado uma nova capacidade ao perfil de usuário do colaborador para poder visualizar a mídia em grid e seus atributos

Nova capacidade ao colaborador

---

wp-content/themes/tema-conselhos/classes/ModelosDePaginas/AgendaConselho/PaginaAgendaConselho.php

Foi adicionado a data de atualizações na página de agenda dos sites dos conselhos

Adicionado data de atualizações em agenda dos sites dos conselhos

---

wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/LoopSingle/LoopSingleNoticiaPrincipal.php
wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/Tag.php
wp-content/themes/sme-portal-institucional/classes/init.php
wp-content/themes/sme-portal-institucional/style.css
wp-content/themes/sme-portal-institucional/tag.php

Criamos a página que lista as noticias com a TAG correspondente.
Removemos a lista de categorias no final da noticia e adicionamos a lista de Tags cadastradas.

Criando pagina para lista de noticias por tags

---

wp-content/themes/tema-conselhos/functions.php

Foi criado uma condição para usuários controlando a visualização dos cards

foi adicionado condição para o usuário para visualizar o card correto

---

wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/LoopSingle/LoopSingleNoticiaPrincipal.php
wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/Tag.php
wp-content/themes/sme-portal-institucional/style.css

Foi criada a paginação para página de Tags e o mesmo executa quando ultrapassa a quantidade de 12 posts por página.
Foi adicionado uma imagem placeholder para posts que não tem imagem destacada.

criado paginação e placeholder de imagem para tags

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-portal-institucional/classes/assets/css/construtor.css

Foi adicionado ao admin opções de cores para cada coluna do construtor de páginas.
Foi adicionado ao CSS espaço entre as linhas dos botões

foi adicionado opções de cores e espaço entre linhas

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-portal-institucional/classes/assets/css/construtor.css

A sanfona do construtor inicia agora todas fechadas.
Adicionado setas para indicar que é possível abrir,
Quando selecionada, mudar a cor da guia selecionada.

ajustes na abertura da sanfona, cor e setas

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php

Foram adicionadas novos tipos de colunas 1/3 e 3/1 para o construtor de páginas do portal

Adicionado novas colunas 1/3 e 3/1 no construtor

---

wp-content/themes/acervodigital/assets/css/style-admin.css
wp-content/themes/acervodigital/core/acf.php
wp-content/themes/acervodigital/core/classes/ctp.php
wp-content/themes/acervodigital/core/classes/tag.php
wp-content/themes/acervodigital/core/classes/taxonomia.php
wp-content/themes/acervodigital/core/enqueue.php
wp-content/themes/acervodigital/core/modify.php
wp-content/themes/acervodigital/front-page.php
wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/ArchiveOrganograma/ArchiveOrganograma.php
wp-content/themes/sme-portal-institucional/classes/assets/css/construtor.css
wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/tema-conselhos/functions.php

Foi desenvolvido o admin para o repositorio e o modulo de cadastro de acervo com os requisitos da história

desenvolvimento do admin com cadastro de acervo

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-portal-institucional/classes/assets/css/construtor.css

Foi criado a condição para troca de H1 para H2 nas colunas 3/1 e 1/3, Fonte do Botão .

Modificações no H2, Botão e fonte

---

_acervo/wp-content/themes/acervodigital/core/classes/tag.php

Foi desenvolvido a criação do palavras chaves para o custom post type acervo

criação de palavras chaves

---

_acervo/wp-content/themes/acervodigital/core/classes/taxonomia.php

Implementação das categorias para o custom post type acervo

criação das categorias do acervo

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/tema-dres/classes/ModelosDePaginas/PaginaInicial/PaginaInicial.php
wp-content/themes/tema-dres/classes/ModelosDePaginas/PaginaInicial/PaginaInicialEscolares.php
wp-content/themes/tema-dres/classes/ModelosDePaginas/PaginaMaisNoticias/PaginaMaisNoticias.php
wp-content/themes/tema-dres/classes/TemplateHierarchy/ArchiveAgenda/ArchiveAgenda.php
wp-content/themes/tema-dres/classes/TemplateHierarchy/ArchiveAgenda/ArchiveAgendaGetDatasEventos.php
wp-content/themes/tema-dres/classes/Usuarios/Administrador/Administrador.php
wp-content/themes/tema-dres/classes/Usuarios/Editor/Editor.php
wp-content/themes/tema-dres/classes/tutorial/tutorial.php
wp-content/themes/tema-dres/functions.php

Implantação de melhorias no tema das DREs, permissionamento de usuários Administrador e Editor.
Implantação de cadastro e visualizações de tutoriais no admin

melhorias, tutoriais e permissionamentos nas DREs

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-portal-institucional/classes/assets/css/construtor.css

-Adicionado cor branca na sanfona ativa
- Espaços entre botões ajustados
- Modelo de botões trocado pelo modelo de botões LP.

ajustes nos botões, espaços e sanfona

---

.gitignore
wp-content/themes/acervodigital/404.php
wp-content/themes/acervodigital/archive-acervo.php
wp-content/themes/acervodigital/assets/css/construtor.css
wp-content/themes/acervodigital/assets/css/style.css
wp-content/themes/acervodigital/construtor.php
wp-content/themes/acervodigital/core/acf.php
wp-content/themes/acervodigital/core/classes/ctp.php
wp-content/themes/acervodigital/core/classes/taxonomia.php
wp-content/themes/acervodigital/core/enqueue.php
wp-content/themes/acervodigital/core/notices.php
wp-content/themes/acervodigital/core/suport.php
wp-content/themes/acervodigital/core/tutorial.php
wp-content/themes/acervodigital/core/users/user.php
wp-content/themes/acervodigital/footer.php
wp-content/themes/acervodigital/functions.php
wp-content/themes/acervodigital/header-front.php
wp-content/themes/acervodigital/single-acervo.php

Criado modelo de páginas com construtor de layout no admin do acervo digital

implementando construtor de páginas no acervo digital

---

wp-content/themes/acervodigital/assets/css/style.css
wp-content/themes/acervodigital/core/suport.php
wp-content/themes/acervodigital/header-front.php
wp-content/themes/acervodigital/header.php

Registro de Menu no admin Wordpress e condicional de menu Front

Registro de menu wordpress no painel admin

---

wp-content/themes/acervodigital/assets/css/acf.css.php
wp-content/themes/acervodigital/assets/css/custom-styles-acf.css
wp-content/themes/acervodigital/assets/css/style.css
wp-content/themes/acervodigital/core/acf.php
wp-content/themes/acervodigital/front-page.php
wp-content/themes/acervodigital/header-front.php
wp-content/themes/acervodigital/header.php

Redirecionamento do logo para o portal SME.
Bloco de Busca com administração de conteudo pelo admin
Blocos de categorias na home com seleção no admin

redirecionamento do logo para o portal, categorias e banner de busca

---

wp-content/themes/acervodigital/core/classes/taxonomia.php

Registro de Taxonomia para autor , setor e idioma no core do wordpress

registro de taxonomia para autor, setor e idioma

---

wp-content/themes/acervodigital/assets/css/construtor.css
wp-content/themes/acervodigital/single-acervo.php
wp-content/themes/acervodigital/taxonomy-palavra.php

REsultado de tag clicada com páginação

Resultado da tag clicada com paginação

---

wp-content/themes/acervodigital/core/utilities.php

Habilitado e configurado no admin a lixeira para medias com permissionamento

habilitado lixeira para midias

---

wp-content/themes/acervodigital/archive-acervo.php
wp-content/themes/acervodigital/archive-teste.php
wp-content/themes/acervodigital/assets/css/style.css
wp-content/themes/acervodigital/front-page.php
wp-content/themes/acervodigital/search.php
wp-content/themes/acervodigital/searchform.php

Página de busca por termo para Acervo Digital

busca por termo acervo digital

---

wp-content/themes/sme-portal-institucional/classes/assets/js/mapa-dres.js

Foi feito um ajusto no script que controla o SVG do Mapa da DRE

ajuste de hover no mapa da Dre

---

wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/ArchiveOrganograma/ArchiveOrganograma.php
wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/ArchiveOrganograma/ArchiveOrganogramaRodape.php
wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/Tag.php
wp-content/themes/sme-portal-institucional/search.php

Adicionado Decreto no organograma e download
Removido DREs das buscas do Portal
Forçando Loop de somente publicados em Tags do portal

Adequação Portal SME - Tag, busca e organograma

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-portal-institucional/classes/assets/css/construtor.css

Foi feita mudanças no layout dos botoes, abas e divisores
Foi adicionado a sanfona padrão com o Mapa das Dres e Editor com fundo

evolução e melhorias no construtor de páginas

---

wp-content/themes/acervodigital/sistema-semanas.php

Coletando dados para contabilizar downloads de documento e visualizações

coleta de dados para acessos e downloads acervo

---

wp-content/themes/acervodigital/search.php
wp-content/themes/acervodigital/searchform.php

Foi desenvolvido a busca avançada para o acervo com filtros

implementado busca avançada com filtros

---

wp-content/themes/acervodigital/single-acervo.php

Foi criado o loop para documentos do acervo que sejam particionados

adicionado loop de botoes para documentos particionados

---

wp-content/themes/tema-dres/classes/TemplateHierarchy/LoopSingle/LoopSingleNoticiaPrincipal.php
wp-content/themes/tema-dres/classes/TemplateHierarchy/tag.php
wp-content/themes/tema-dres/classes/init.php
wp-content/themes/tema-dres/style.css
wp-content/themes/tema-dres/tag.php

Foi criado a página de tags para as Noticias das DREs

Página de tags DREs

---

wp-content/themes/acervodigital/assets/css/style.css
wp-content/themes/acervodigital/core/classes/taxonomia.php
wp-content/themes/acervodigital/error_log
wp-content/themes/acervodigital/search-filtros.php
wp-content/themes/acervodigital/search.php
wp-content/themes/acervodigital/single-acervo.php
wp-content/themes/acervodigital/taxonomy-categoria_acervo.php
wp-content/themes/acervodigital/taxonomy-idioma.php

Foi criado paginas para resultados de categorias e palavras chaves para filtrar os conteúdos do acervo digital

criado paginas para resultado de categorias e palavras chaves

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-portal-institucional/classes/assets/css/construtor.css

Foi criado link para imagens de cada tipo de coluna no construtor e foi gravado os novos campos no ACF.
Foi adicionado uma nova classe de cor para os botões com a cor azul escuro

criado link para imagens e cor de botao

---

wp-content/themes/acervodigital/assets/css/style.css
wp-content/themes/acervodigital/search.php
wp-content/themes/acervodigital/searchform.php
wp-content/themes/acervodigital/taxonomy-categoria_acervo.php

Alteração do layout da página com resultados de busca exibindo uma imagem no novo formato e correção da url da busca no formulário para o ambiente de homoligação

modificacao da pagina de busca quando vazia

---

wp-content/themes/acervodigital/functions.php

Ocultar as taxonomias da lateral do editor do Acervo no painel do Wordpress

Ocultar taxonomias acervo

---

wp-content/themes/acervodigital/core/classes/taxonomia.php
wp-content/themes/acervodigital/single-acervo.php

Alterar a taxonomia do Acervo de "Modalidade" para "Nível/Etapa/Modalidade"

Alterar nome da taxonomia do Acervo

---

wp-content/themes/sme-portal-institucional/footer.php
wp-content/themes/sme-portal-institucional/style.css

Adequação do rodapé no portal do SME para o novo layout aprovado pela secretaria.

Adequacao do novo rodape do portal

---

wp-content/themes/sme-portal-institucional/search.php

Correção do caminho da imagem padrão no resultado de busca, alterando para pegar sempre a URL da home caso ela seja alterada por alguma necessidade

correcao do caminho da imagem no resultado da busca

---

wp-content/themes/sme-portal-institucional/classes/Breadcrumb/Breadcrumb.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptConcursos.php
wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/PaginaConcursos/PaginaConcursos.php
wp-content/themes/sme-portal-institucional/classes/init.php
wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/sme-portal-institucional/pagina-concursos.php
wp-content/themes/sme-portal-institucional/search.php
wp-content/themes/sme-portal-institucional/search_concurso.php
wp-content/themes/sme-portal-institucional/style.css

Criação da nova página de concursos públicos com filtros por data de validade, data de homologação, data de ultima chamada, status e por cargo.

Pagina de concursos com filtros

---

wp-content/themes/acervodigital/front-page.php

Correção das imagens que aparecem no fundo das categorias

exibir imagem no fundo da categoria

---

wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaInicial/PaginaInicial.php
wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacao.php
wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoBusca.php
wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoCategorias.php
wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoEventos.php
wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoSlide.php
wp-content/themes/tema-ceus/classes/init.php
wp-content/themes/tema-ceus/css/jquery.multiselect.css
wp-content/themes/tema-ceus/footer.php
wp-content/themes/tema-ceus/functions.php
wp-content/themes/tema-ceus/get_category.php
wp-content/themes/tema-ceus/header.php
wp-content/themes/tema-ceus/js/jquery.multiselect.css
wp-content/themes/tema-ceus/js/jquery.multiselect.js
wp-content/themes/tema-ceus/pagina-programacao-ceu.php
wp-content/themes/tema-ceus/search.php
wp-content/themes/tema-ceus/search_old.php
wp-content/themes/tema-ceus/search_programacao.php
wp-content/themes/tema-ceus/style.css

Página para a programação dos CEUs com destaque principal, filtro de busca, categorias e eventos em destaque.

Pagina principal programacao CEUs

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php

Ajuste nas sessão de Abas do construtor para não repetir o identificador da aba

Ajuste nas Abas do construtor

---

wp-content/themes/acervodigital/single-acervo.php

Ajuste nas métricas individuais de cada arquivo para corrigir o contador.

Ajuste na metrica de cada arquivo

---

wp-content/themes/acervodigital/_construtor.php
wp-content/themes/acervodigital/assets/css/_construtor.css
wp-content/themes/acervodigital/assets/css/style.css
wp-content/themes/acervodigital/core/classes/ctp.php
wp-content/themes/acervodigital/core/classes/taxonomia.php
wp-content/themes/acervodigital/front-page.php
wp-content/themes/acervodigital/functions.php
wp-content/themes/acervodigital/search.php
wp-content/themes/acervodigital/single-acervo.php
wp-content/themes/acervodigital/taxonomy-categoria_acervo.php
wp-content/themes/acervodigital/taxonomy-idioma.php
wp-content/themes/acervodigital/taxonomy-palavra.php

Ajuste no botão de ver detalhes para visualização do arquivo antes de baixa-lo

Ajuste botao ver detalhes

---

wp-content/themes/sme-portal-institucional/style.css

Ajuste no tamanho das fontes nos cards do tema

Tamanho da fonte dos cards

---

wp-content/themes/sme-portal-institucional/search.php

Alteração na busca do portal para aceitar termos completos separando por palavras para aumentar a quantidade de resultados

altaracao busca para termos e palavras

---

wp-content/themes/sme-portal-institucional/search.php

Ajuste na busca para buscar por palavras e termos completos

Ajuste na busca

---

wp-content/themes/acervodigital/assets/js/script.js
wp-content/themes/acervodigital/searchform.php

- Inclusão de mensagem para busca vazia
- Bloqueio de envio do formulário em caso de todos os campos estiverem vazio
- Buscar por titulo ou palavra chave

Incluir mensagem busca vazia

---

wp-content/themes/acervodigital/assets/css/style.css
wp-content/themes/acervodigital/search.php
wp-content/themes/acervodigital/single-acervo.php
wp-content/themes/acervodigital/taxonomy-categoria_acervo.php
wp-content/themes/acervodigital/taxonomy-idioma.php
wp-content/themes/acervodigital/taxonomy-palavra.php

Incluir link nas palavras-chave nos resultados de buscas e nas taxonomias, formatar link para botões

incluir link nas palavras chave

---

wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/tema-dres/classes/Usuarios/Colaborador/Colaborador.php

Exibição do menu "Opções Gerais" para usuários do tipo Editor

Alterar menu para editores

---

wp-content/themes/acervodigital/assets/css/style.css
wp-content/themes/acervodigital/single-acervo.php

Validação de campos de acordo com o tipo de documento selecionado no painel

Tipo de documento com validacao de campos

---

wp-content/themes/acervodigital/single-acervo.php

Campo para inserir link do Diário Oficial no painel administrativo
Botão para o Diário Oficial condicionado ao preenchimento do campo no painel

Campo de link e botao para o Diario Oficial

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/PaginaMaisNoticias/PaginaMaisNoticiasDestaques.php
wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/LoopSingle/LoopSingleRelacionadas.php

Ajuste no looping de notícias para para adequação dos apontamos no ASES Web

Adequacao noticias para acessibilidade

---

wp-content/themes/acervodigital/core/acf.php
wp-content/themes/acervodigital/front-page.php
wp-content/themes/acervodigital/functions.php
wp-content/themes/acervodigital/search.php
wp-content/themes/acervodigital/single-acervo.php
wp-content/themes/acervodigital/taxonomy-categoria_acervo.php
wp-content/themes/acervodigital/taxonomy-idioma.php
wp-content/themes/acervodigital/taxonomy-palavra.php

Padronizar nomenclatura de inclusão no acervo e páginas do site

Padronizar nomenclaturas do acervo

---

wp-content/themes/acervodigital/functions.php
wp-content/themes/acervodigital/search.php
wp-content/themes/acervodigital/single-acervo.php
wp-content/themes/acervodigital/taxonomy-categoria_acervo.php
wp-content/themes/acervodigital/taxonomy-idioma.php
wp-content/themes/acervodigital/taxonomy-palavra.php

Verificação de campos vazios no cadastro do acervo para não serem exibidos na visualização
Definição do idioma padrão no cadastro do acervo

Validacao de campos vazio na visualizacao

---

wp-content/themes/acervodigital/core/classes/ctp.php
wp-content/themes/acervodigital/functions.php

Ocultar o itens Downloads e Acesso do menu do painel

Ocultar acessos e downloads do menu

---

wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/LoopSingle/LoopSingleNoticiaPrincipal.php
wp-content/themes/sme-portal-institucional/style.css

Formatação do subtítulo das noticias para itálico e sem negrito

Estilo do subtitulo das noticias

---

wp-content/themes/tema-dres/classes/ModelosDePaginas/PaginaInicial/PaginaInicialNoticiasDestaquePrimaria.php
wp-content/themes/tema-dres/classes/ModelosDePaginas/PaginaInicial/PaginaInicialNoticiasDestaqueSecundarias.php
wp-content/themes/tema-dres/classes/TemplateHierarchy/LoopSingle/LoopSingleNoticiaPrincipal.php
wp-content/themes/tema-dres/classes/TemplateHierarchy/LoopSingle/LoopSingleRelacionadas.php
wp-content/themes/tema-dres/style.css

Criação do campo Subtítulo nas notícias das DREs
Exibição dos subtítulos nas noticias caso não esteja vazio
Verificação do status dos destaques principais das DREs

Subtitulo e validacao de noticias no destaque

---

wp-content/themes/acervodigital/assets/css/style.css
wp-content/themes/acervodigital/core/acf.php
wp-content/themes/acervodigital/core/enqueue.php
wp-content/themes/acervodigital/footer.php
wp-content/themes/acervodigital/header-front.php
wp-content/themes/acervodigital/header.php
wp-content/themes/sme-portal-institucional/footer.php
wp-content/themes/tema-conselhos/footer.php
wp-content/themes/tema-conselhos/functions.php
wp-content/themes/tema-conselhos/header.php
wp-content/themes/tema-conselhos/style.css
wp-content/themes/tema-dres/footer.php
wp-content/themes/tema-dres/functions.php
wp-content/themes/tema-dres/header.php
wp-content/themes/tema-dres/style.css

Aplicação do novo rodapé nos temas das DREs, Conselhos e Acervo Digital

Aplicacao novo rodape em todos os portais

---

wp-content/themes/acervodigital/assets/css/style.css
wp-content/themes/acervodigital/search.php
wp-content/themes/acervodigital/single-acervo.php
wp-content/themes/acervodigital/taxonomy-categoria_acervo.php
wp-content/themes/acervodigital/taxonomy-idioma.php
wp-content/themes/acervodigital/taxonomy-palavra.php

Exibição de formato para arquivos particionados no Acervo

Formato de arquivos particionados

---

wp-content/themes/acervodigital/assets/css/style.css
wp-content/themes/acervodigital/search.php
wp-content/themes/acervodigital/taxonomy-categoria_acervo.php
wp-content/themes/acervodigital/taxonomy-idioma.php
wp-content/themes/acervodigital/taxonomy-palavra.php

Aviso para os usuários quando o acervo possui arquivos particionados
Em caso de particionado o botão "fazer download" é suprimido

Aviso de arquivos particionados

---

wp-content/themes/acervodigital/core/acf.php
wp-content/themes/acervodigital/core/classes/taxonomia.php
wp-content/themes/acervodigital/core/metricas.php

- Remoção da permissão para edição das categorias do Acervo para editores
- Adicionado o menu Métricas para Editores

Permissoes para editores

---

wp-content/themes/sme-portal-institucional/search.php

Remover dos filtro de busca o tipo de publicação 'Concurso'

Remover concurso dos filtros de busca

---

wp-content/themes/tema-dres/classes/ModelosDePaginas/PaginaMaisNoticias/PaginaMaisNoticiasDestaques.php

Ocultar o nome do portal em Mais Notícias nos portais das DREs

Ocultar nome do portal nas DREs

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/PaginaConcursos/PaginaConcursos.php
wp-content/themes/sme-portal-institucional/search_concurso.php

Automação da data Última Atualização na página e na busca de Concursos

Automatizar data ultima edicao dos concursos

---

wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/tema-conselhos/functions.php
wp-content/themes/tema-dres/functions.php

Ordenação de usuários pela coluna Setor

Ordenacao de usuarios pela coluna setor

---

wp-content/themes/tema-conselhos/functions.php
wp-content/themes/tema-dres/functions.php

Alteração do script de cards dos conselhos para resolver conflito com o carregamento de biblioteca de mídias nas notícias.

Exibicao na biblioteca de midia

---

wp-content/themes/tema-dres/classes/ModelosDePaginas/PaginaMaisNoticias/PaginaMaisNoticias.php
wp-content/themes/tema-dres/classes/ModelosDePaginas/PaginaMaisNoticias/PaginaMaisNoticiasDestaques.php
wp-content/themes/tema-dres/classes/ModelosDePaginas/PaginaMaisNoticias/PaginaMaisNoticiasMaisLidas.php

Criação do botão Outras Notícias para inserir o link de notícias do portal antigo.

Botao noticias mais antigas

---

wp-content/themes/tema-dres/classes/ModelosDePaginas/PaginaInicial/PaginaInicial.php
wp-content/themes/tema-dres/classes/ModelosDePaginas/PaginaInicial/PaginaInicialAcervo.php
wp-content/themes/tema-dres/classes/ModelosDePaginas/PaginaInicial/PaginaInicialAgenda.php
wp-content/themes/tema-dres/classes/init.php

Criação de sessão para incluir o links para o Acervo Digital dentro dos portais das DREs.

Link para o Acervo Digital

---

wp-content/themes/sme-portal-institucional/search.php
wp-content/themes/tema-dres/search.php

- Inclusão das páginas e posts das DREs na busca principal do portal
- Correção do caminho da imagem nos resultados de buscas do tema das DREs

Inclusao de filtros na busca para as DREs

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-portal-institucional/style.css

Criação de novas sessões dentro do construtor de páginas para a listagem de contatos

Novos blocos usuarios no construtor de paginas

---

_git_plugins/email-admin-dre/email-admin-dre.php
_git_plugins/email-admin/email-admin.php

- Notificação por e-mail para administradores e editores do portal para noticias e páginas que forem para revisão pendente
- Notificação por e-mail para administradores das DREs para noticias e páginas que forem para revisão pendente

Notificacao para revisao pendente

---

wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/ArchiveContato/ArchiveContato.php
wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/ArchiveContato/ArchiveContatoMetabox.php

Inclusão do campo de site para o mapa das DREs

inclusao campo de site para o mapa das dres

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-portal-institucional/classes/assets/css/construtor.css
wp-content/themes/sme-portal-institucional/footer.php
wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/sme-portal-institucional/header.php
wp-content/themes/sme-portal-institucional/style.css

Implementação da nova home do Portal de Comunicação

Implementacao da nova home do portal

---

wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoEventos.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleCabecalho.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleNoticiaPrincipal.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleRelacionadas.php
wp-content/themes/tema-ceus/style.css

- Implementação de página com eventos que acontece em mais de um CEU
- Adequação de acessibilidade da página

Pagina com mais de um evento dos CEUs

---

_git_plugins/grupo-editores/grupo-editores.php

Alteração nas permissões de arquivos nos grupos de editores

Alteracao permissionamento de arquivos

---

_git_plugins/grupo-ceus/grupo-ceus.php
wp-content/themes/tema-ceus/classes/Cpt/CptUnidades.php
wp-content/themes/tema-ceus/classes/Usuarios/Colaborador/Colaborador.php
wp-content/themes/tema-ceus/classes/init.php
wp-content/themes/tema-ceus/functions.php

- Reestruturação do plugin de Grupo de Editores para que seja estendido para unidades e eventos
- Inclusão de filtro por unidades e eventos de cada grupo para colaboradores

Cadastro de unidades dos CEUs

---

wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoEventos.php
wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoSlide.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleCabecalho.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleNoticiaPrincipal.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleRelacionadas.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidades.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesCabecalho.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesSlide.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesTabs.php
wp-content/themes/tema-ceus/classes/init.php
wp-content/themes/tema-ceus/functions.php
wp-content/themes/tema-ceus/js/mapsceus-leaflet.js
wp-content/themes/tema-ceus/search.php
wp-content/themes/tema-ceus/single-unidade.php
wp-content/themes/tema-ceus/style.css

- Criação das páginas individuais das unidades dos CEUs
- Ajuste do filtro de busca para o novo formato de unidades
- Ajuste do resultado de busca para o novo formato de unidades
- Ajuste da página individual dos eventos para o novo formato de unidade

Pagina individual dos CEUs

---

wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaUnidades/PaginaUnidades.php
wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaUnidades/PaginaUnidadesMapa.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleRelacionadas.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesTabs.php
wp-content/themes/tema-ceus/classes/init.php
wp-content/themes/tema-ceus/footer.php
wp-content/themes/tema-ceus/functions.php
wp-content/themes/tema-ceus/header.php
wp-content/themes/tema-ceus/pagina-unidades.php
wp-content/themes/tema-ceus/style.css

Implementar página geral do CEUs com listagem de unidades, marcadores nos mapas e localização do usuário.

Pagina geral dos CEUs

---

wp-content/themes/sme-portal-institucional/classes/assets/css/construtor.css

- Manter o conteúdo fechado da sanfone no mobile

Fechar conteudo sanfone na versao mobile

---

wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/tema-ceus/functions.php
wp-content/themes/tema-conselhos/functions.php
wp-content/themes/tema-dres/functions.php

- Ativação da barra superior com botão Editar páginas para editores e administrador do Portal, DREs, Conselhos e CEUs

Barra superior para editar páginas

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-portal-institucional/js/scripts.js
wp-content/themes/sme-portal-institucional/style.css

- Inserção de link nas imagens do slide;
- Fechamento dos acessos rápidos no segundo click;
- Alinhamento dos links do acesso rápido;
- Alteração do tamanho da fonte das noticias em destaque;
- Alteração na cor das setas do slide.

Melhoras na home page

---

_git_plugins/grupo-ceus/grupo-ceus.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesCabecalho.php
wp-content/themes/tema-ceus/functions.php

Alteração no menu administrativo do painel por tipos de usuários

Alteracoes no menu administrativo do painel

---

_git_plugins/email-admin-ceu/email-admin-ceu.php
_git_plugins/grupo-ceus/grupo-ceus.php
wp-content/themes/tema-ceus/classes/init.php
wp-content/themes/tema-ceus/functions.php

- Alteração no perfil de Editor para melhor uso para os editores das DREs
- Disparo de e-mails em Eventos e Unidades que foram para revisão para admins e seus respectivos editores da mesma DRE.

Perfil de Editores DREs e disparo de emails para revisao

---

wp-content/themes/sme-portal-institucional/footer.php
wp-content/themes/sme-portal-institucional/header.php
wp-content/themes/sme-portal-institucional/style.css

Inserção de Redes Sociais de modo dinâmico no topo e rodapé podendo inserir as informações e ícone como imagem ou da biblioteca Font Awsome.

Redes sociais dinamica no topo e rodape

---

wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/sme-portal-institucional/js/wp-admin.js

- Alteração do tipo do campo alt no admin de text para textarea
- Alteração da string de texto "Texto alternativo" para "Descrição para acessibilidade"

Acessibilidade nas imagens

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-portal-institucional/construtor/construtor-mais_lidas_1_1.php
wp-content/themes/sme-portal-institucional/construtor/construtor-mais_lidas_pag_1_1.php
wp-content/themes/sme-portal-institucional/construtor/construtor-noticias_destaque_1_1.php
wp-content/themes/sme-portal-institucional/construtor/construtor-outras_noticias_1_1.php
wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/sme-portal-institucional/style.css

- Novo componente do Construtor para listar noticias em destaque
- Novo componente do Construtor para mostrar as mais lidas
- Novo componente do Construtor para mostrar as noticias das DREs
- Novo componente do Construtor para exibir a lista completa de noticias

Novo layout de noticias

---

_git_plugins/email-admin-ceu/email-admin-ceu.php

Enviar o nome da unidade no assunto e no corpo do e-mail ao enviar a publicação para revisão

Enviar a unidade no assunto e corpo do email

---

wp-content/themes/sme-portal-institucional/construtor/construtor-noticias_1_2.php
wp-content/themes/sme-portal-institucional/construtor/construtor-noticias_1_3b.php
wp-content/themes/sme-portal-institucional/construtor/construtor-noticias_1b_3.php
wp-content/themes/sme-portal-institucional/construtor/construtor-noticias_2_2.php
wp-content/themes/sme-portal-institucional/construtor/construtor-noticias_3_1b.php
wp-content/themes/sme-portal-institucional/construtor/construtor-noticias_3b_1.php
wp-content/themes/sme-portal-institucional/construtor/construtor-noticias_categ_1_1.php

- Ajuste do componente de Noticias do construtor para exibir a imagem destacada de cada noticia na listagem por categoria.

Ajuste no componente de noticias para exibir as imagens destacadas

---

wp-content/themes/sme-portal-institucional/classes/LoadDependences.php
wp-content/themes/sme-portal-institucional/classes/init.php

Ocultar campos de contato para o Custom Post Type Contatos

ocultar campos do CPT contatos

---

wp-content/themes/sme-portal-institucional/classes/Cpt/CptPosts.php

Remover campos "Destaque" e "Posição Destaque" da listagem de noticias.

Remover campos do cadastro e listagem de noticias

---

wp-content/themes/sme-portal-institucional/functions.php

- Alterações do nome da página "Página Inicial" para "Alerta da Página Inicial" em Opções Gerais do portal
- Remoção da página "Página de Notícias" dentro de Opções Gerais do portal

Remocao e alteracao nos campos de configuracoes gerais

---

wp-content/themes/sme-portal-institucional/classes/Usuarios/CamposAdicionais.php
wp-content/themes/sme-portal-institucional/css/admin.css
wp-content/themes/sme-portal-institucional/functions.php

- Incluir a coluna Páginas dentro da lista de usuários mostrando a quantidade de páginas por usuário com a opção de filtragem de páginas;
- Alteração da colunas "Posts" para "Notícias" na lista de usuários no admin.

Coluna paginas dentro da lista de usuarios

---

wp-content/themes/sme-portal-institucional/classes/init.php

- Ocultar o tipo de post "Cards" do menu do painel administrativo

Ocultar o tipo de post Cards no menu do admin

---

wp-content/themes/acervodigital/core/acf.php
wp-content/themes/acervodigital/core/tutorial.php
wp-content/themes/sme-portal-institucional/classes/tutorial/tutorial.php
wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/tema-conselhos/classes/tutorial/tutorial.php
wp-content/themes/tema-conselhos/functions.php
wp-content/themes/tema-dres/classes/tutorial/tutorial.php
wp-content/themes/tema-dres/functions.php

- Tradução do botão de "Update" para "Atualizar" no tema do Conselho, DREs, Portal e Acervo
- Alteração do texto de "Ver documentação" para "Ver tutorial" no tema do Conselho, DREs, Portal e Acervo

Visualizacao dos tutoriais no admin

---

wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoEventos.php
wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoSlide.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleNoticiaPrincipal.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleRelacionadas.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesTabs.php
wp-content/themes/tema-ceus/classes/Usuarios/Colaborador/Colaborador.php
wp-content/themes/tema-ceus/classes/Usuarios/Editor/Editor.php
wp-content/themes/tema-ceus/functions.php
wp-content/themes/tema-ceus/search.php
wp-content/themes/tema-ceus/style.css

- Correção de datas únicas para eventos
- Exibição de todas as datas para eventos com mais de um período
- Exibição do horário na pagina interna do eventos
- Exibição do responsável pela unidade
- Criação de novo campo para link de inscrições do eventos
- Ocultar submenus da sessão de Eventos para Editores e Colaboradores
- Remover opção de cadastro de Unidades para Editores e Colaboradores

Melhorias de usabilidade

---

_git_plugins/email-admin/email-admin.php
_git_plugins/grupo-editores/grupo-editores.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptContato.php
wp-content/themes/sme-portal-institucional/classes/Usuarios/Colaborador/Colaborador.php
wp-content/themes/sme-portal-institucional/classes/Usuarios/EnviarParaRevisao.php
wp-content/themes/sme-portal-institucional/functions.php

- Atribuição de Contatos para os Colaboradores
- Habilitar revisão para contato e disparo de e-mail aos admins para aprovação

Permissoes de acesso e disparo de emails

---

wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/tema-conselhos/css/admin.css
wp-content/themes/tema-conselhos/functions.php
wp-content/themes/tema-dres/css/admin.css
wp-content/themes/tema-dres/functions.php

- Alteração do tema utilizado no painel admin
- Ocultamento dos botões de atualizações do painel

Ocultar versoes e alteracao de tema do painel

---

wp-content/themes/sme-portal-institucional/footer.php
wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/sme-portal-institucional/header.php
wp-content/themes/sme-portal-institucional/style.css

- Inclusão de parâmetros no menu para melhoria da acessibilidade no portal

Inclusao de parametros de acessibilidade no menu

---

wp-content/themes/sme-portal-institucional/classes/Cpt/CptContato.php
wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/ArchiveContato/ArchiveContato.php
wp-content/themes/sme-portal-institucional/classes/init.php
wp-content/themes/sme-portal-institucional/functions.php

- No mapa de contatos das DREs modificação das informações de contatos para novo padrão de campos personalizados
- Em Contatos SME no painel inclusão da coluna "Grupos" juntamente com o filtro

Contatos das DREs e coluna de grupos em Contatos

---

wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoEventos.php
wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoSlide.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleNoticiaPrincipal.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleRelacionadas.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesCabecalho.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesSlide.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesTabs.php
wp-content/themes/tema-ceus/css/admin.css
wp-content/themes/tema-ceus/functions.php
wp-content/themes/tema-ceus/search.php
wp-content/themes/tema-ceus/style.css

- Alteração da exibição de horas
- Alteração da nomenclatura de abas
- Exibição dos novos campos criados
- Ocultar botão de mídia no cadastro o CEU

Melhorias cadastro dos ceus

---

wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoEventos.php
wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoSlide.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleNoticiaPrincipal.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleRelacionadas.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesSlide.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesTabs.php
wp-content/themes/tema-ceus/functions.php
wp-content/themes/tema-ceus/search.php

- Tradução das datas para português
- Inclusão do link de mídia na descrição
- Alteração de eventos relacionados a Grandes Eventos

Alteracao data e tipo de eventos

---

wp-content/themes/sme-portal-institucional/classes/assets/js/mapa-dres.js

- Ajuste acordeom para fechar no click
- Ativação do titulo do acordeom ao clicar no mapa

Correcao acordeon no mapa das DREs

---

wp-content/themes/acervodigital/functions.php

- Ocultar os tipos de usuários Assinante e Autor do cadastro/edição de usuário para que os mesmos não possam ser atribuídos e nenhum usuário.

Ocultar funcoes de usuarios

---

wp-content/themes/acervodigital/functions.php

- Inclusão do campo setor
- Ordenação de usuários por setor
- Ocultação de menus por tipo de setor

Inclusao do setor para usuarios e permissoes de acesso

---

wp-content/themes/tema-dres/classes/ModelosDePaginas/PaginaInicial/PaginaInicialEndereco.php

- Inclusão do campo complemento no endereço da DRE e no mapa

Inclusao do campo complemento no endereco

---

_git_plugins/grupo-ceus/grupo-ceus.php
_git_plugins/grupo-editores/grupo-editores.php

- Alterar o nome da sessão de Grupos de Colabores para Grupos no portal
- Alterar o nome da sessão de Editores Ceus para Grupo no portal do CEUs

Alterar nome dos cpt Grupos de Colaboradores para Grupos

---

_git_plugins/email-admin/email-admin.php
wp-content/themes/sme-portal-institucional/classes/Usuarios/Colaborador/Colaborador.php
wp-content/themes/sme-portal-institucional/classes/Usuarios/Editor/Editor.php
wp-content/themes/sme-portal-institucional/functions.php

- Liberação de acesso ao Cadastro de Concursos para usuários do tipo Colaborador
- Envio de Concursos para aprovação para usuários do tipo Colaborador
- Envio de e-mail para Administradores e Editores para aprovação dos Concursos cadastrados ou editados.

Cadastro de concursos para colaboradores

---

wp-content/themes/sme-portal-institucional/search.php

Ocultar os itens do Organograma nos filtros de buscar do portal

Remover filtros de busca nao utilizados

---

wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/ArchiveContato/ArchiveContato.php

- Inclusão do link nos contatos do mapa das DREs para campos do tipo URL

Link no campo do tipo url no mapa das dres

---

wp-content/themes/acervodigital/core/classes/taxonomia.php
wp-content/themes/acervodigital/functions.php

- Alteração do nome do campo de "Adicionar nova" para "Adicionar novo"
- Alteração do nome do campo de "Enviar nova mídia" para "Enviar novo arquivo"
- Alteração do nome do campo de "Editar mídia" para "Editar arquivo"
- Alteração da classe de registro de taxonomia para receber o valor no campo do botão

Padrao de nomenclatura de campos

---

wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/tema-ceus/functions.php
wp-content/themes/tema-conselhos/functions.php
wp-content/themes/tema-dres/functions.php

- Desabilitar os tipo usuários Assinante e Autor;
- Alterar a nomenclatura de Contribuidor para Colaborador

Ocultar tipos de usuarios e alterar nomenclatura

---

wp-content/themes/sme-portal-institucional/construtor/construtor-organograma_1_1.php
wp-content/themes/tema-conselhos/classes/ModelosDePaginas/PaginaCards/PaginaCards.php

- Aplicação do comparador de data para exibição da ultima data de atualização no organograma do Portal;
- Modificação e melhoria na exibição da ultima data de atualização do tema dos Conselhos.

Atualizacao automatica da data de atualizacao

---

wp-content/themes/tema-conselhos/classes/init.php

- Desativar os tipos de publicação Cadastro de Abas e Cadastro de Botões
- Desativar os modelos de páginas Abas e Botões

Ocultar os CPTs de cadastro de Abas e Botoes

---

wp-content/themes/sme-portal-institucional/classes/assets/css/construtor.css

- Ocultar linhas externas de tabelas
- Manter tabela com 100% de largura

Ocultar linhas externa e manter largura total nas tabelas

---

wp-content/themes/tema-ceus/functions.php
wp-content/themes/tema-ceus/js/wp-admin.js
wp-content/themes/tema-dres/functions.php
wp-content/themes/tema-dres/js/wp-admin.js

- Alteração do tipo de campo no descritivo das imagens
- Alteração no nome dos campos

Acessibillidade nas imagens

---

wp-content/themes/tema-conselhos/classes/Breadcrumb/Breadcrumb.php

Remoção dos Cards na jornada do usuário

Remocao de Cards na jornada do usuario

---

wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoEventos.php
wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoSlide.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleCabecalho.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleNoticiaPrincipal.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleRelacionadas.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesSlide.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesTabs.php
wp-content/themes/tema-ceus/functions.php
wp-content/themes/tema-ceus/search.php
wp-content/themes/tema-ceus/style.css

- Criação de eventos em serie (mesmo evento em mais de uma unidade)
- Listagem de todos os locais na pagina individual do evento
- Ajuste da busca para buscar o novo modelo de evento
- Ajuste dos slides para o novo padrão dos eventos
- Ajuste do bloco de eventos na página de Eventos para o novo padrão

Criacao de eventos em serie

---

wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleNoticiaPrincipal.php

- Inclusão de turmas no cadastro de eventos

Turmas no cadastro de evento

---

wp-content/themes/tema-ceus/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/tema-ceus/classes/assets/css/construtor.css

- Criação de novos componentes do Construtor de Páginas
- Melhorias de componentes do Construtor de Páginas

Pagina inicial CEU

---

wp-content/themes/acervodigital/single-acervo.php

- Novo campo Volume/Edição do acervo

Campo Volume Edicao do Acervo

---

wp-content/themes/acervodigital/footer.php
wp-content/themes/tema-ceus/footer.php

- Remoção do selo de acessibilidade do rodapé do Acervo Digital
- Remoção do selo de acessibilidade do rodapé do portal dos CEUs

Remocao do selo de acessibilidade

---

wp-content/themes/acervodigital/assets/css/style.css
wp-content/themes/acervodigital/construtor.php
wp-content/themes/acervodigital/footer.php
wp-content/themes/acervodigital/functions.php
wp-content/themes/acervodigital/header.php
wp-content/themes/acervodigital/searchform.php

Nova pagina inicial do Acervo Digital

Nova pagina inicial Acervo

---

wp-content/themes/sme-portal-institucional/functions.php

Redirecionamento de links via htaccess

Redirecionamento de links

---

wp-content/themes/sme-portal-institucional/search.php

- Ordenação do filtro de busca por site
- Ordenação do filtro de busca por tipo de conteúdo

Ordenacao do filtro de busca

---

wp-content/themes/acervodigital/assets/css/style.css
wp-content/themes/acervodigital/construtor.php
wp-content/themes/acervodigital/footer.php
wp-content/themes/acervodigital/header.php
wp-content/themes/acervodigital/searchform.php

Implementação da busca simples e avançada na home do Acervo em versão Desktop e Mobile

Busca simples e avancada

---

wp-content/themes/acervodigital/assets/css/style.css
wp-content/themes/acervodigital/assets/js/script.js
wp-content/themes/acervodigital/functions.php
wp-content/themes/acervodigital/search.php
wp-content/themes/acervodigital/searchform.php
wp-content/themes/acervodigital/single-acervo.php

Resultados da busca

---

wp-content/themes/acervodigital/assets/css/style.css
wp-content/themes/acervodigital/construtor.php
wp-content/themes/acervodigital/search.php
wp-content/themes/acervodigital/single-acervo.php

Detalhes do documento do Acervo

Detalhes do documento Acervo

---

wp-content/themes/sme-portal-institucional/construtor/construtor-botao_1_1.php
wp-content/themes/sme-portal-institucional/construtor/construtor-botao_1_2.php
wp-content/themes/sme-portal-institucional/construtor/construtor-botao_1_3b.php
wp-content/themes/sme-portal-institucional/construtor/construtor-botao_1b_3.php
wp-content/themes/sme-portal-institucional/construtor/construtor-botao_2_2.php
wp-content/themes/sme-portal-institucional/construtor/construtor-botao_3_1.php
wp-content/themes/sme-portal-institucional/construtor/construtor-botao_3_1b.php
wp-content/themes/sme-portal-institucional/construtor/construtor-botao_3_2.php
wp-content/themes/sme-portal-institucional/construtor/construtor-botao_3_3.php
wp-content/themes/sme-portal-institucional/construtor/construtor-botao_3b_1.php
wp-content/themes/sme-portal-institucional/construtor/construtor-botao_4_1.php
wp-content/themes/sme-portal-institucional/construtor/construtor-botao_4_2.php
wp-content/themes/sme-portal-institucional/construtor/construtor-botao_4_3.php
wp-content/themes/sme-portal-institucional/construtor/construtor-botao_4_4.php

Botões responsivo do Construtor de Páginas

Botoes responsivo das paginas

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-portal-institucional/classes/assets/css/construtor.css
wp-content/themes/sme-portal-institucional/construtor/construtor-bloco_noticias_timer_1_1.php
wp-content/themes/sme-portal-institucional/construtor/construtor-slide_timer_1_1.php
wp-content/themes/sme-portal-institucional/functions.php

Agendamento de noticias no Slide e Bloco de Noticias com data e hora de exibição

Agendar noticias no Slide e Bloco de Noticias

---

wp-content/themes/acervodigital/assets/css/style.css
wp-content/themes/acervodigital/search.php
wp-content/themes/acervodigital/single-acervo.php

Moldura padrão para as imagens no resultado de busca e detalhe do documento

Capa do documento com tamanho padrao

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/PaginaConcursos/PaginaConcursos.php
wp-content/themes/sme-portal-institucional/search_concurso.php

Correção do filtro de Cargos na página de Concursos de título para ID

Alterar filtro concursos de titulo por id

---

wp-content/themes/sme-portal-institucional/classes/Lib/Util.php
wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/sme-portal-institucional/style.css

- Submenu padrão para as páginas de projetos;
- Submenu automático dentro das subpáginas;
- Exibição do Rótulo no lugar do título em caso de preenchido

Menu padrao paginas programas

---

wp-content/themes/tema-ceus/functions.php

- Alterar o texto do titulo (placeholder) no cadastro e/ou edição de uma publicação no Sobre o CEU

Alterar placeholder cadastro novo CEU

---

wp-content/themes/tema-ceus/classes/Cpt/CptPosts.php
wp-content/themes/tema-ceus/functions.php

- Inclusão da Coluna "Destaque Home" nos eventos
- Ordenação dos Eventos por destaque
- Inclusão e exclusão em massa para marcação de destaques
- Filtragem de posts por Destaque na página de Eventos

Destaques para a pagina de Programacao dos CEUs

---

wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoEventos.php
wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoSlide.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleCabecalho.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleRelacionadas.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesSlide.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesTabs.php
wp-content/themes/tema-ceus/functions.php
wp-content/themes/tema-ceus/search.php

- Alteração do nome de recorte de tamanho das imagens (Thumbnails)
- Ocultar recortes não utilizados por editores/colaboradores no admin

Alterar nome recorte de imagens e ocultar nao utilizados

---

wp-content/themes/acervodigital/assets/css/style.css
wp-content/themes/acervodigital/search.php
wp-content/themes/acervodigital/single-acervo.php

- Ocultar campos não preenchidos do Acervo Digital;
- Ocultar autor caso não possua no resultado de busca.

Ocultar campos vazios no Acervo Digital

---

wp-content/themes/tema-naapa/classes/TemplateHierarchy/LoopQuebrada/LoopQuebrada.php
wp-content/themes/tema-naapa/classes/TemplateHierarchy/LoopQuebrada/LoopQuebradaComentarios.php
wp-content/themes/tema-naapa/classes/init.php
wp-content/themes/tema-naapa/comments-helper.php
wp-content/themes/tema-naapa/comments.php
wp-content/themes/tema-naapa/footer.php
wp-content/themes/tema-naapa/functions.php
wp-content/themes/tema-naapa/js/post-like.js
wp-content/themes/tema-naapa/js/script.js
wp-content/themes/tema-naapa/js/wp-admin.js
wp-content/themes/tema-naapa/style.css

- Inclusão da sessão de comentários em "O que rola na quebrada?"
- Validação dos campos do formulário

Comentarios na sessao O que rola na quebrada

---

wp-content/themes/acervodigital/core/acf.php

Ocultar o item "Página Inicial" dentro de Opções Gerais no administrativo do Acervo Digital

Ocultar item Pagina Inicial

---

wp-content/themes/acervodigital/single-acervo.php

Na página interna do Acervo no botão "Voltar ao resultado de busca" alterar o link para que leve para a página anterior ao invés da home.

Link voltar para a busca no Acervo

---

wp-content/themes/sme-portal-institucional/classes/Cpt/CptPosts.php
wp-content/themes/sme-portal-institucional/functions.php

Ocultar colunas do plugin _Yoast_ na listagem de noticias e páginas

Ocultar colunas do Yoast nas listagens

---

wp-content/themes/acervodigital/assets/css/style-admin.css
wp-content/themes/acervodigital/assets/js/script-admin.js

Exibição de alerta caso o usuário desvincule o arquivo do Acervo para lembra-lo de remover o arquivo da biblioteca.

Exibir mensagem em caso de remocao do arquivo no Acervo

---

wp-content/themes/sme-portal-institucional/classes/Lib/Util.php
wp-content/themes/sme-portal-institucional/footer.php

Inclusão de ícone e texto de acessibilidade para links que são externos ao Portal.

Icone e texto de acessibilidade para link externo

---

wp-content/themes/sme-portal-institucional/classes/Lib/Util.php
wp-content/themes/sme-portal-institucional/footer.php

reversao para ajuste no codigo

Revert "Icone e texto de acessibilidade para link externo"

---

wp-content/themes/sme-portal-institucional/classes/Lib/Util.php
wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-portal-institucional/footer.php
wp-content/themes/sme-portal-institucional/loop-single.php

Inclusão de ícone e texto para acessibilidades em links que levem para fora do Portal

Incluir icone e texto para acessibilidade em links externos

---

_git_plugins/create-user-without-send-email/create-user-without-send-email.php
_git_plugins/create-user-without-send-email/php/cuwp.php
wp-content/themes/sme-portal-institucional/header.php
wp-content/themes/sme-portal-institucional/style.css

Correção do disparo de e-mail para novos usuários no site do Portal

Correcao disparo de emails novo usuario

---

wp-content/themes/tema-naapa/classes/assets/css/construtor.css

Inclusão da opção de botão na cor preta dentro do Construtor de Páginas

Botao na cor preta dentro do construtor

---

wp-content/themes/tema-naapa/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/tema-naapa/construtor/construtor-turma_naapa.php
wp-content/themes/tema-naapa/footer.php
wp-content/themes/tema-naapa/functions.php
wp-content/themes/tema-naapa/style.css

- Implantação do elemento "Turma do NAAPA" no admin do site;
- Criação do componente "Turma do NAAPA" no Construtor de Páginas para implementação do mesmo na páginas do site

Implantacao turma do naapa

---

wp-content/themes/sme-portal-institucional/footer.php
wp-content/themes/tema-ceus/footer.php
wp-content/themes/tema-conselhos/footer.php
wp-content/themes/tema-dres/footer.php
wp-content/themes/tema-naapa/footer.php

Inclusão do link para o site da prefeitura do rodapé dos portais.

Inclusao do link da prefeitura no rodape

---

wp-content/themes/tema-naapa/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/tema-naapa/footer.php
wp-content/themes/tema-naapa/functions.php
wp-content/themes/tema-naapa/search.php
wp-content/themes/tema-naapa/style.css

Implementação da busca do site com filtro por tipo de publicação

Busca do site com filtro por tipo de publicacao

---

wp-content/themes/tema-naapa/functions.php
wp-content/themes/tema-naapa/header.php

Criação da sessão "Analytics" dentro do menu "Opções Gerais" no admin do portal para inserção do código de acompanhamento do Google Analytics

Campo para insercao do Google Analytics

---

wp-content/themes/sme-portal-institucional/classes/Cpt/CptPages.php

Inclusão da coluna "Modificado por" na listagem de páginas mostrando o ultimo usuário a editar o conteúdo da página.

Coluna com o ultimo usuario a editar a pagina

---

wp-content/themes/sme-portal-institucional/classes/assets/css/construtor.css
wp-content/themes/sme-portal-institucional/construtor/construtor-botao.php
wp-content/themes/sme-portal-institucional/construtor/construtor-botao_1_1.php
wp-content/themes/sme-portal-institucional/functions.php

Alinhamento do botões no Construtor de página.

Alinhamento do botoes do construtor

---

wp-content/themes/sme-portal-institucional/classes/Cpt/Cpt.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptAgendaSecretario.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptBotao.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptCard.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptConcursos.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptContato.php
wp-content/themes/sme-portal-institucional/classes/Cpt/cptProgramaProjeto.php

Ativar opções de Revisões para todos os _Custom Post Types_ do tema.

Ativar revisao para custom post type

---

wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleNoticiaPrincipal.php

Ocultar itens vazios dentro da página de eventos dos CEUs

Ocultar itens vazios na pagina do evento

---

wp-content/themes/sme-portal-institucional/classes/Cpt/CptContato.php

Exibir campo Titulo no cadastro do contatos em homologação

Exibir campo titulo nos contatos em homologacao

---

wp-content/themes/tema-ceus/footer.php
wp-content/themes/tema-ceus/functions.php

Melhoria na busca de unidades por endereço e por nome da unidade

Busca por unidade e endereco no mapa de unidades

---

wp-content/themes/sme-portal-institucional/construtor/construtor-noticias_destaque.php
wp-content/themes/sme-portal-institucional/construtor/construtor-noticias_destaque_1_1.php

Alteração do título no componente "Notícias em trio de destaque" do Construtor de Páginas caso o campo "Titulo de destaque" seja preenchido em Notícias

Alterar titulo do componente Trio de destaque

---

wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesCabecalho.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesTabs.php

Padronizar nomenclatura do Horário de Funcionamento das unidades e serviços oferecidos pelos CEUs

Padronizar nomenclatura do horario de funcionamento

---

wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoBusca.php
wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoCategorias.php
wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoEventos.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleNoticiaPrincipal.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesTabs.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/Search/SearchForm.php
wp-content/themes/tema-ceus/footer.php
wp-content/themes/tema-ceus/header.php
wp-content/themes/tema-ceus/style.css

Adaptações no tema do Portal do CEUs para a versão mobile usando como referencia o protótipo desenvolvido.

Adaptacoes para versao mobile do tema do Portal dos CEUs

---

wp-content/themes/tema-dres/classes/assets/css/pagina-inicial.css

Alterar a cor da caixa de destaque das notícias na home no tema das DREs

Alterar cor da caixa de destaque na home

---

wp-content/themes/tema-ceus/functions.php

Enviar as publicações para revisão após edição feita por usuários do perfil Colaborador

Enviar o Sobre o CEU para revisao apos edicao pelo perfil de colaborador

---

_git_plugins/email-admin-ceu/email-admin-ceu.php
wp-content/themes/tema-ceus/classes/Usuarios/EnviarParaRevisao.php

Envio de email em massa para Administradores e Editores para aprovação de Eventos e Sobre o CEU

Envio de email em massa para aprovacao de publicacoes

---

wp-content/themes/sme-portal-institucional/archive-agendanew.php
wp-content/themes/sme-portal-institucional/classes/Cpt/Cpt.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptAgendaSecretarioNew.php
wp-content/themes/sme-portal-institucional/classes/LoadDependences.php
wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/ArchiveAgenda/ArchiveAgendaAjaxCalendario.php
wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/ArchiveAgenda/ArchiveAgendaAjaxCalendarioNew.php
wp-content/themes/sme-portal-institucional/classes/init.php
wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/sme-portal-institucional/js/my_query.js

Melhorias na inclusão de Eventos na Agenda do Secretário usando como referencia os protótipos desenvolvidos.

Melhorias na inclusao de eventos da agenda

---

wp-content/themes/sme-portal-institucional/construtor/construtor-organograma_1_1.php
wp-content/themes/sme-portal-institucional/css/orgchart.css
wp-content/themes/sme-portal-institucional/footer.php

Ajustando o conflito do script do organograma com o script que inclui ícones em URLs para links externos.

Remover links do organograma para a regra de icone de links externos

---

wp-content/themes/sme-portal-institucional/construtor/construtor-organograma_1_1.php

Exibição da ultima data e hora de atualização na página do Organograma.

Exibicao da data de ultima atualizacao do Organograma

---

wp-content/themes/sme-portal-institucional/construtor/construtor-acesso_rapido.php
wp-content/themes/sme-portal-institucional/construtor/construtor-acesso_rapido_1_1.php

Suporte para opção de botão sem ícone no elemento Menu de Acesso Rápido do Construtor de Página.

Opção de botão de Acesso Rapido sem icone

---

wp-content/themes/tema-ceus/classes/Usuarios/Administrador/Administrador.php
wp-content/themes/tema-ceus/classes/Usuarios/Colaborador/Colaborador.php
wp-content/themes/tema-ceus/classes/Usuarios/Editor/Editor.php
wp-content/themes/tema-ceus/classes/init.php

Permissões de acesso, edição e exclusão de unidades na sessão Sobre o CEU para usuários do tipo Colaborador e Editor

Permissoes de unidades para perfis de colaboradores e editores

---

wp-content/themes/sme-portal-institucional/construtor/construtor-contato_camadas.php
wp-content/themes/sme-portal-institucional/construtor/construtor-contato_camadas_1_1.php
wp-content/themes/sme-portal-institucional/construtor/construtor-contato_individual.php
wp-content/themes/sme-portal-institucional/construtor/construtor-contato_individual_1_1.php

Opção de subtítulos para os elementos do Construtor de Páginas "Contatos em Camadas" e "Contatos Individuais"

Opcao de subtitulo para contatos individuais e em camadas

---

wp-content/themes/acervodigital/assets/css/style-admin.css
wp-content/themes/acervodigital/assets/js/script-admin.js

Inclusão de mensagens de aviso na inclusão de mídia tanto na opção de Grid como Lista dentro do menu de Arquivos no Acervo Digital.

Inclusao de aviso no upload de midias do Acervo

---

wp-content/themes/acervodigital/assets/css/style.css

Ajuste na altura da linha da paginação na versão mobile do Acervo Digital.

Ajuste altura da linha na pagina mobile

---

wp-content/themes/sme-portal-institucional/construtor/construtor-noticias_dres.php
wp-content/themes/sme-portal-institucional/construtor/construtor-noticias_dres_1_1.php

Ajuste no componente do Construtor de Páginas "Notícias das DREs" para que não pegue notícias que tenham o mesmo ID em portais diferentes.

Noticias das DREs no Portal de Comunicacao

---

wp-content/themes/tema-ceus/functions.php

Ocultar unidades e eventos para Editores e Colaboradores caso o filtro "Minhas Unidades" e "Meus Eventos" estejam ativos no painel administrativo.

Ocultar eventos e unidades no filtro Meus Eventos e Minhas Unidades

---

wp-content/themes/sme-portal-institucional/classes/assets/js/mapa-dres.js

Rolagem da tela até as informações de contato ao clicar no mapa das DREs.

Rolagem da tela ao clicar no mapa

---

wp-content/themes/tema-ceus/classes/Cpt/CptUnidades.php
wp-content/themes/tema-ceus/functions.php

Ocultar o filtro e a coluna "Categorias" na listagem de Unidades na sessão "Sobre o CEU" no painel administrativo.

Ocultar filtro e coluna Categorias na listagem de Unidades

---

wp-content/themes/acervodigital/search.php

Inclusão do filtro "Publico Alvo" e alteração do filtro "Idioma" para que seja mostrado apenas em casos onde haja mais de um idioma para ser filtrado.

Filtro de Publico Alvo e Idioma

---

wp-content/themes/tema-ceus/classes/Cpt/CptPosts.php
wp-content/themes/tema-ceus/functions.php

Filtro de Eventos por unidade via seletor ou nome da unidade na coluna "Unidades" no admintrativo.

Filtro de eventos por unidade

---

wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaUnidades/PaginaUnidadesMapa.php
wp-content/themes/tema-ceus/functions.php
wp-content/themes/tema-ceus/style.css

Alerta de uso da localização do usuário no mapa de unidades dos CEUs

Alerta de uso da localizacao no mapa de unidades

---

wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaUnidades/PaginaUnidadesMapa.php
wp-content/themes/tema-ceus/footer.php
wp-content/themes/tema-ceus/style.css

Inclusão do filtro por zona no mapa de unidades do CEUs

Filtro por zona no mapa de unidades do CEUs

---

wp-content/themes/sme-portal-institucional/functions.php

Correção do numeral do mês de dezembro no filtro por mês da Agenda do Secretário no painel administrativo do Portal.

Ajuste do numeral do mes de dezembro no filtro por data

---

wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaUnidades/PaginaUnidadesMapa.php
wp-content/themes/tema-ceus/footer.php
wp-content/themes/tema-ceus/style.css

Alteração da lista de unidades, busca e filtro por zona para o modelo _collapse_ dentro do mapa de Unidades dos CEUs na versão _mobile_.

Lista de unidades filtros e busca com collapse no mobile

---

wp-content/themes/sme-portal-institucional/search.php
wp-content/themes/sme-portal-institucional/style.css

Alteração do refinamento dos resultados de busca na versão mobile do Portal para o modelo de _pop-up_

Busca refinada na versao mobile do Portal

---

wp-content/themes/acervodigital/assets/js/script.js
wp-content/themes/acervodigital/searchform.php

Ajuste da validação dos campos na Busca Avançada do Acervo Digital na versão mobile.

Ajuste validacao busca avancada versao mobile

---

wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/sme-portal-institucional/pagina-busca.php
wp-content/themes/sme-portal-institucional/style.css
wp-content/themes/tema-conselhos/pagina-busca.php
wp-content/themes/tema-conselhos/style.css
wp-content/themes/tema-dres/pagina-busca.php
wp-content/themes/tema-dres/style.css

Melhorias no refinamento e resultados de busca do Portal, Conselhos e DREs

Melhorias no refinamento e resultados de busca

---

wp-content/themes/acervodigital/assets/js/script-admin.js

Link direto para remoção dos arquivos no Acervo Digital

Link direto para remocao do arquivo

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-portal-institucional/classes/assets/css/construtor.css
wp-content/themes/sme-portal-institucional/style.css
wp-content/themes/tema-ceus/header.php

- Exibição do menu de acessibilidade na versão mobile do Portal e CEUs;
- Ajuste no menu de Acesso Rápido do Portal na versão mobile;
- Ajuste no Trio de Destaques no site do Portal na versão mobile.

Ajustes versao mobile do portal e ceus

---

wp-content/themes/sme-portal-institucional/footer.php
wp-content/themes/sme-portal-institucional/header.php
wp-content/themes/sme-portal-institucional/style.css

- Ajuste no alinhamento do menu de acessibilidade;
- Ajuste no tamanho das fontes do Slide de Destaque;
- Ajuste no posicionamento do texto do elemento do Construtor "Trio de destaque";
- Ajuste no tamanho do logo no rodapé e do selo de acessibilidade.

Melhorias na versao mobile do portal

---

wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaUnidades/PaginaUnidadesMapa.php
wp-content/themes/tema-ceus/footer.php

Ocultar emails e telefones secundários no mapa de Unidades do Portal dos CEUs

Ocultar emails e telefones secundarios no mapa

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-portal-institucional/classes/assets/css/construtor.css
wp-content/themes/sme-portal-institucional/construtor/construtor-video.php
wp-content/themes/sme-portal-institucional/construtor/construtor-video_1_1.php
wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/sme-portal-institucional/style.css

Alteração para que o incorporador de vídeo automático do WordPress e do Construtor de Páginas inclua os vídeo mantendo a proporção da página e mantendo-se responsivo na versão mobile.

Videos responsivos e adaptivos nas paginas

---

wp-content/themes/acervodigital/export-users.php
wp-content/themes/acervodigital/functions.php
wp-content/themes/sme-portal-institucional/export-users.php
wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/tema-ceus/export-users.php
wp-content/themes/tema-ceus/functions.php

Exportar a relação de usuários no Portal, Portal dos CEUs e Acervo Digital com as seguintes informações:
- Nome de usuário
- Email
- Função
- Grupos pertencentes (Portal e CEUs)
- Setor (Portal e Acervo Digital)

Exportar relacao de usuarios em csv

---

wp-content/themes/tema-ceus/functions.php
wp-content/themes/tema-ceus/header.php

Criação da sessão "Analytics" dentro do menu "Opções Gerais" para a inclusão do código de acompanhamento do Google Analytics dentro do admin do Portal do CEUs

Inclusao do campo para a insercao do google analytics

---

wp-content/themes/sme-portal-institucional/css/admin.css
wp-content/themes/sme-portal-institucional/functions.php

Mudar subpáginas para Privado diretamente do editor da página principal.

Mudar subpaginas para Privado no editor de paginas

---

wp-content/themes/sme-portal-institucional/functions.php

Redirecionamento de arquivos que possuem caracteres especiais na url

Redirecionamento de arquivos com caracter especial na url

---

wp-content/themes/sme-portal-institucional/functions.php

Redirecionamento de links via htaccess para URLs com ou sem barra no final ( / )

Redirecionamento de links com e sem barra no final

---

wp-content/themes/sme-portal-institucional/archive-agendanew.php
wp-content/themes/sme-portal-institucional/classes/LoadDependences.php
wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/ArchiveAgendaNew/ArchiveAgendaAjaxCalendarioNew.php
wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/ArchiveAgendaNew/ArchiveAgendaGetDatasEventosNew.php
wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/ArchiveAgendaNew/ArchiveAgendaNew.php
wp-content/themes/sme-portal-institucional/classes/init.php

Inclusão dos marcadores de compromissos no calendário dentro do novo modelo da Agenda do Secretario

Incluir marcador de compromissos nova agenda

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php

Dentro do item do Construtor de Páginas "Habilitar Menu Lateral" ao selecionar as paginas do menu habitar a opção de incluir um link externo ao menu.

Inclusao de link externo para menu lateral

---

_git_plugins/coressoapi/coressoapi.php

Integração do login do WordPress com a API do CoreSSO

Integracao do login do WordPress com o CoreSSO

---

wp-content/themes/acervodigital/single-acervo.php

Alteração do visualizador de documentos dentro do Acervo Digital

Alterar visualizado de documentos

---

wp-content/themes/intranet/footer.php
wp-content/themes/intranet/style.css

Padronização do rodapé utilizado nos Portais sem o selo de acessibilidade.

Padronizar rodape sem o selo de acessibilidade

---

wp-content/themes/intranet/footer.php
wp-content/themes/intranet/style.css

Inclusão do botão e funcionalidade de "voltar ao topo" nas páginas na Intranet

Inclusao do botao voltar ao topo

---

wp-content/themes/intranet/classes/Cpt/CptDestaques.php

Filtro de Recados por Tag dentro do painel administrativo do WordPress

Filtro de recados por tag no admin

---

wp-content/themes/intranet/classes/assets/css/pagina-login.css
wp-content/themes/intranet/functions.php

Inclusão do texto de orientação de senha após o link de recuperar a senha no login.

Texto de orientacao no link de recuperar a senha

---

_git_plugins/coressoapi/coressoapi.php
wp-content/themes/intranet/classes/LoadDependences.php
wp-content/themes/intranet/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/intranet/classes/TemplateHierarchy/ArchiveAgenda/ArchiveAgenda.php
wp-content/themes/intranet/classes/TemplateHierarchy/ArchiveAgendaNew/ArchiveAgendaGetDatasEventosNew.php
wp-content/themes/intranet/classes/TemplateHierarchy/ArchiveAgendaNew/ArchiveAgendaNew.php
wp-content/themes/intranet/classes/assets/css/construtor.css
wp-content/themes/intranet/classes/assets/css/slick-theme.css
wp-content/themes/intranet/classes/assets/css/slick.css
wp-content/themes/intranet/classes/assets/js/ion.calendar-2.0.2/js/ion.calendar.js
wp-content/themes/intranet/classes/assets/js/slick.js
wp-content/themes/intranet/classes/init.php
wp-content/themes/intranet/construtor/construtor-banner_whatsapp_2_2.php
wp-content/themes/intranet/construtor/construtor-botao.php
wp-content/themes/intranet/construtor/construtor-calendario_1_1.php
wp-content/themes/intranet/construtor/construtor-cursos_destaques_2_2.php
wp-content/themes/intranet/construtor/construtor-form_news_1_2.php
wp-content/themes/intranet/construtor/construtor-mural_recados_1_1.php
wp-content/themes/intranet/construtor/construtor-mural_recados_destaques_1_2.php
wp-content/themes/intranet/construtor/construtor-portais_sistemas_carrossel_1_1.php
wp-content/themes/intranet/js/scripts.js

Criação dos elementos do Construtor de página para utilização na home do portal:
- Carrossel de Portais e Sistemas
- Destaque de Recados
- Destaques de Cursos
- Agenda de Eventos
- Assinatura de Newsletter
- Assinatura de WhatsApp

Construtor de paginas home page intranet

---

_git_plugins/wordpress-login-count/wordpress-login-count.php
wp-content/themes/intranet/classes/Usuarios/CamposAdicionais.php
wp-content/themes/intranet/classes/assets/css/pagina-inicial.css
wp-content/themes/intranet/footer.php
wp-content/themes/intranet/functions.php
wp-content/themes/intranet/style.css

- Estilos para a página de feedback
- Contador de acessos de usuários
- Pop-up para chamadas para avalição do site

Pagina de Feedback e contator de acessos

---

wp-content/themes/intranet/classes/assets/css/construtor.css
wp-content/themes/intranet/classes/assets/css/pagina-inicial.css
wp-content/themes/intranet/construtor/construtor-bloco_rede.php
wp-content/themes/intranet/construtor/construtor-cursos_1_1.php
wp-content/themes/intranet/construtor/construtor-faq_1_1.php
wp-content/themes/intranet/construtor/construtor-mural_recados_1_1.php
wp-content/themes/intranet/construtor/construtor-mural_recados_destaques_1_2.php
wp-content/themes/intranet/construtor/construtor-portais_sistemas_carrossel_1_1.php
wp-content/themes/intranet/header-forms.php
wp-content/themes/intranet/header.php
wp-content/themes/intranet/search.php
wp-content/themes/intranet/style.css

Versão mobile para o tema da Intranet

Versao mobile do tema Intranet

---

wp-content/themes/sme-portal-institucional/functions.php

Remover o submenu "Categoria de Contatos"

Ocultar submenu Categorias de Contato

---

wp-content/themes/intranet/footer.php
wp-content/themes/intranet/functions.php
wp-content/themes/intranet/header.php
wp-content/themes/intranet/pagina-perfil.php

Pagina de Perfil de usuário e edição de senha junto ao CoreSSO

Pagina de perfil e alteracao de senha

---

wp-content/themes/intranet/construtor/construtor-portais_sistemas_1_1.php

Inclusão do botão de limpar filtro na página Portais e Sitemas

Botao limpar filtro Portais e sistemas

---

wp-content/themes/intranet/pagina-perfil.php
wp-content/themes/intranet/style.css

Inclusão do campo RG na página de perfil dos usuários

Inclusao do campo RG no perfil

---

wp-content/themes/intranet/classes/Cpt/CptParceiros.php
wp-content/themes/intranet/classes/init.php

Publicações personalizadas (Custom Post Type) para empresas parceiras.

Publicacoes personalizadas para cadastro de Parceiros

---

wp-content/themes/intranet/cartao-educador.php
wp-content/themes/intranet/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/intranet/classes/assets/css/construtor.css
wp-content/themes/intranet/construtor/construtor-card_subpaginas_1_1.php
wp-content/themes/intranet/construtor/construtor-card_subpaginas_internas_1_1.php
wp-content/themes/intranet/construtor/construtor-cartao_educador.php
wp-content/themes/intranet/construtor/construtor-empresas-parceiras.php
wp-content/themes/intranet/construtor/construtor-sanfona.php

Elementos do Construtor de Páginas:
- Empresas Parceiras
- Cartão do Educador
- Card Subpaginas
- Card Subpaginas Internas

Elementos do Construtor Empresas parceiras e Cartao do educador

---

wp-content/themes/tema-dres/header.php

Link para a home do Portal no logotipo do tema das DREs

Link do logotipo para home do Portal

---

wp-content/themes/sme-portal-institucional/functions.php

Exibir seletor de grupos dentro de contatos e fazer a relação de seleção entre eles

Exibir seletor de grupos em contatos

---

wp-content/themes/tema-ceus/functions.php

Ativar categorias ascendentes em eventos do CEUs

ativar categorias ascendentes em eventos

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-portal-institucional/classes/assets/css/construtor.css
wp-content/themes/sme-portal-institucional/construtor/construtor-concursos_sme.php

- Melhorias de layout na página de concursos
- Integração com o Construtor de Páginas

Melhoria pagina concursos

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-portal-institucional/classes/assets/css/construtor.css
wp-content/themes/sme-portal-institucional/construtor/construtor-concursos_sme.php

Melhoria na Página de Concursos opção "Ver todos os concursos"

Concursos botao ver todos

---

wp-content/themes/sme-portal-institucional/classes/assets/css/construtor.css
wp-content/themes/sme-portal-institucional/construtor/construtor-concursos_sme.php

Nova página de Concursos versão responsivo para dispositivos mobile.

Pagina concursos versao mobile

---

wp-content/themes/intranet/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/intranet/classes/assets/css/construtor.css
wp-content/themes/intranet/construtor/construtor-ingressos_plateia_1_1.php

Ingressos do Plateia na sessão Benefícios da Intranet

Intranet beneficios plateia

---

wp-content/themes/tema-ceus/functions.php
wp-content/themes/tema-ceus/style.css

Remoção de unidades duplicadas ao fazer uma busca na pagina Unidades

Remocao de unidades duplicadas na busca

---

wp-content/themes/tema-ceus/functions.php

Permissão para edição de links permanentes somente para administradores

Permissao de edicao da url por admin

---

wp-content/themes/sme-portal-institucional/classes/Lib/Util.php
wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php

- Aumento da largura da tela para monitores maiores
- Diminuição do tamanho no menu lateral
- Melhoria no Construtor de Páginas para páginas com menu lateral no admin

Melhorias no menu lateral

---

wp-content/themes/acervodigital/search.php

Ordenar filtro "Ano" por ondem decrescente

Ordenar filtro ano por ordem decrescente

---

wp-content/themes/sme-portal-institucional/classes/Usuarios/CamposAdicionais.php
wp-content/themes/sme-portal-institucional/classes/Usuarios/Colaborador/Colaborador.php
wp-content/themes/sme-portal-institucional/classes/Usuarios/Editor/Editor.php
wp-content/themes/sme-portal-institucional/classes/init.php
wp-content/themes/sme-portal-institucional/css/admin.css
wp-content/themes/sme-portal-institucional/export-users.php
wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/sme-portal-institucional/js/wp-admin.js

- Criação do item de menu Setor no admin
- Ordenação e filtro por setor na edição dos usuários
- Histórico de edição de grupos em cada usuário

Altarecao no campo setor dos usuarios

---

wp-content/themes/sme-portal-institucional/style.css

Alterar o tamanho do _container_(conteúdo da pagina) em telas com resolução maior que 1260px

Breakpoints do container

---

wp-content/themes/sme-portal-institucional/footer.php
wp-content/themes/sme-portal-institucional/style.css

Botão "Voltar ao topo" em todas as paginas do Portal na versão mobile

Incluir botao voltar ao topo na versao mobile

---

wp-content/themes/sme-portal-institucional/classes/assets/css/construtor.css
wp-content/themes/sme-portal-institucional/construtor/construtor-concursos_sme.php

Página de Concursos caso não haja nenhum resultado na busca

Concursos nenhum resultado

---

wp-content/themes/sme-portal-institucional/css/admin.css
wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/sme-portal-institucional/js/wp-admin.js

Exibir mensagem de alerta nas páginas de upload de mídia

Alerta ao fazer upload de midia

---

_git_plugins/flamingo/admin/admin-functions.php
_git_plugins/flamingo/admin/admin.php
_git_plugins/flamingo/admin/css/style-rtl.css
_git_plugins/flamingo/admin/css/style.css
_git_plugins/flamingo/admin/edit-contact-form.php
_git_plugins/flamingo/admin/edit-inbound-form.php
_git_plugins/flamingo/admin/edit-outbound-form.php
_git_plugins/flamingo/admin/includes/SimpleXLSXGen.php
_git_plugins/flamingo/admin/includes/class-contacts-list-table.php
_git_plugins/flamingo/admin/includes/class-inbound-messages-list-table.php
_git_plugins/flamingo/admin/includes/class-outbound-messages-list-table.php
_git_plugins/flamingo/admin/includes/meta-boxes.php
_git_plugins/flamingo/admin/includes/privacy.php
_git_plugins/flamingo/admin/js/script.js
_git_plugins/flamingo/flamingo.php
_git_plugins/flamingo/includes/akismet.php
_git_plugins/flamingo/includes/capabilities.php
_git_plugins/flamingo/includes/class-contact.php
_git_plugins/flamingo/includes/class-inbound-message.php
_git_plugins/flamingo/includes/class-outbound-message.php
_git_plugins/flamingo/includes/comment.php
_git_plugins/flamingo/includes/cron.php
_git_plugins/flamingo/includes/csv.php
_git_plugins/flamingo/includes/formatting.php
_git_plugins/flamingo/includes/functions.php
_git_plugins/flamingo/includes/user.php
_git_plugins/flamingo/languages/readme.txt
_git_plugins/flamingo/license.txt
_git_plugins/flamingo/readme.txt

Mudar o formato do arquivo de exportação do _plugin_ **Flamingo** de CSV para XLSX

Mudar formato de exportacao de dados de csv para xlsx

---

wp-content/themes/tema-dres/classes/TemplateHierarchy/ArchiveAgenda/ArchiveAgendaAjaxCalendario.php
wp-content/themes/tema-dres/classes/TemplateHierarchy/ArchiveAgenda/ArchiveAgendaGetDatasEventos.php

Exibir o marcador de data no calendário quando houver eventos cadastrados

Exibir marcador de data no calendario

---

wp-content/themes/tema-conselhos/classes/Breadcrumb/Breadcrumb.php
wp-content/themes/tema-conselhos/classes/TemplateHierarchy/LoopAgenda/LoopAgenda.php
wp-content/themes/tema-conselhos/classes/TemplateHierarchy/LoopAgenda/LoopAgendaEventos.php
wp-content/themes/tema-conselhos/classes/TemplateHierarchy/LoopAgenda/LoopAgendaPrincipal.php
wp-content/themes/tema-conselhos/classes/init.php
wp-content/themes/tema-conselhos/single-agendaconselho.php

Criar a pagina personalizada para as publicações personalizadas "Agenda"

Pagina post personalizado agenda

---

wp-content/themes/sme-portal-institucional/classes/Cpt/CptSetor.php
wp-content/themes/sme-portal-institucional/classes/init.php
wp-content/themes/sme-portal-institucional/functions.php

- Remover colunas "Categoria" no administrativo dos Setores
- Remover o filtro por categoria no administrativo dos Setores, Agenda e Contato

Melhorias no cadastro de Setor

---

wp-content/themes/acervodigital/single-acervo.php

Inclusão do novo campo "Data da publicação no Diário Oficial"

Novo campo Data do Diario Oficial

---

wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoEventos.php
wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoSlide.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleRelacionadas.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesSlide.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesTabs.php
wp-content/themes/tema-ceus/functions.php
wp-content/themes/tema-ceus/search.php

- Modificar o tamanho padrão das imagens de destaques dos eventos e fotos das unidades no Portal dos CEUs
- Não permitir o upload de imagens menores que 640x350px.

Definir tamanho minimo de imagem

---

wp-content/themes/acervodigital/core/acf.php
wp-content/themes/acervodigital/header.php

- Criação da sub sessão "Analytics" dentro da sessão "Opções Gerais" no admin
- Inclusão do código no cabeçalho do site

Incluir sessao para o codigo do Analytics

---

wp-content/themes/sme-visitas-monitoradas/classes/Cpt/CptCadastroParceiros.php
wp-content/themes/sme-visitas-monitoradas/classes/init.php
wp-content/themes/sme-visitas-monitoradas/functions.php

Cadastro da sessão "Parceiros" no admin do site

CPT Cadastro de parceiros

---

wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleCabecalho.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleNoticiaPrincipal.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleRelacionadas.php

Exibir Eventos em Série dentro de Grandes Eventos

Associar Eventos em Serie com Grandes Eventos

---

wp-content/themes/sme-visitas-monitoradas/classes/LoadDependences.php
wp-content/themes/sme-visitas-monitoradas/classes/ModelosDePaginas/Login/Login.php
wp-content/themes/sme-visitas-monitoradas/classes/ModelosDePaginas/Login/LoginForm.php
wp-content/themes/sme-visitas-monitoradas/classes/assets/css/pagina-login.css
wp-content/themes/sme-visitas-monitoradas/classes/init.php
wp-content/themes/sme-visitas-monitoradas/footer-forms.php
wp-content/themes/sme-visitas-monitoradas/functions.php
wp-content/themes/sme-visitas-monitoradas/header-forms.php
wp-content/themes/sme-visitas-monitoradas/pagina-login.php
wp-content/themes/sme-visitas-monitoradas/style.css

Pagina de Login no site integrando o CoreSSO e o login do WordPress

Pagina de Login

---

wp-content/themes/sme-visitas-monitoradas/classes/ModelosDePaginas/Login/LoginRecuperar.php
wp-content/themes/sme-visitas-monitoradas/classes/assets/css/pagina-login.css
wp-content/themes/sme-visitas-monitoradas/classes/init.php
wp-content/themes/sme-visitas-monitoradas/pagina-recuperar.php

Modelo de página "Recuperar Senha" com integração ao CoreSSO para recuperar a senha dos usuários a partir do RF

Pagina de Recuperar Senha

---

wp-content/themes/tema-dres/classes/TemplateHierarchy/ArchiveAgenda/ArchiveAgendaGetDatasEventos-QUERY-MES-A-MES-DINAMICA.php

Ajustando o conflito de Ajax entre o calendário e a Biblioteca de mídias

Validacao de pagina para carregar itens do calendario

---

wp-content/themes/sme-visitas-monitoradas/classes/LoadDependences.php
wp-content/themes/sme-visitas-monitoradas/classes/assets/css/home.css
wp-content/themes/sme-visitas-monitoradas/classes/assets/css/pagina-login.css
wp-content/themes/sme-visitas-monitoradas/classes/assets/js/home.js
wp-content/themes/sme-visitas-monitoradas/classes/assets/js/pagina-login.js
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-banner_evento.php
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-bloco_de_busca.php
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-carousel_eventos.php
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-newsletter_eventos.php
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-parceiros_do_projeto.php
wp-content/themes/sme-visitas-monitoradas/header.php
wp-content/themes/sme-visitas-monitoradas/home/banner.php
wp-content/themes/sme-visitas-monitoradas/home/busca.php
wp-content/themes/sme-visitas-monitoradas/home/carrossel-cinemas.php
wp-content/themes/sme-visitas-monitoradas/home/carrossel-museus.php
wp-content/themes/sme-visitas-monitoradas/home/logo-parceiros.php
wp-content/themes/sme-visitas-monitoradas/style.css

Template e ajustes no construtor da homepage de Visitas monitoras

template homepage visitas

---

wp-content/themes/sme-portal-institucional/classes/Cpt/CptAgendaSecretarioNew.php
wp-content/themes/sme-portal-institucional/classes/assets/js/ajax-agenda-secretario.js
wp-content/themes/sme-portal-institucional/classes/init.php

Ajustes de titulos e anos da nova agenda do secretário

Ajustes de titulos e anos da nova agenda do secretário

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php

Movimento suave para collapses e ajuste da posição top

Movimento suave para collapses e ajuste da posição top

---

wp-content/themes/tema-ceus/functions.php

Adiciona select na lista de filtros para eventos para ser utilizado com o botão filtrar

Adiciona select na lista de filtros para eventos

---

wp-content/themes/sme-visitas-monitoradas/classes/LoadDependences.php
wp-content/themes/sme-visitas-monitoradas/classes/assets/css/busca.css
wp-content/themes/sme-visitas-monitoradas/classes/assets/js/busca.js
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-bloco_de_busca.php

Adicionado funcoes ao filtro de busca na home de visitas

Adicionado funcoes ao filtro de busca na home

---

wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesTabs.php

Inserção do link na imagem de capa dos eventos dentro da página das unidades do CEUs

Link na imagem do evento dentro da listagem na unidade

---

wp-content/themes/tema-ceus/header.php

troca do href do logo para o portal da educação

troca do href do logo para o portal da educação

---

wp-content/themes/sme-portal-institucional/classes/Cpt/CptAgendaDreBt.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptAgendaDreCs.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptAgendaDreFb.php
wp-content/themes/sme-portal-institucional/classes/Usuarios/Editor/Editor.php
wp-content/themes/sme-portal-institucional/classes/init.php
wp-content/themes/sme-portal-institucional/functions.php

- Criação das publicações das Agendas de cada DRE
- Criação do menu para agrupamento das Agendas das DREs
- Exibição das Agendas definido no Grupo de Usuários de cada DRE para usuários do tipo Editor

Agenda das DREs no Portal

---

wp-content/themes/sme-visitas-monitoradas/functions.php
wp-content/themes/sme-visitas-monitoradas/header.php

Inclusão do campo do Google Analytics no administrativo e no cabeçalho do tema

Inclusao campos para o Google Analytics

---

wp-content/themes/tema-ceus/functions.php

Redirecionar o usuário ao editar um evento que não pertença ao mesmo grupo que ele.

Nao permitir a edicao do evento para usuarios fora do grupo

---

_git_plugins/email-admin-ceu/email-admin-ceu.php
wp-content/themes/tema-ceus/functions.php

Validar os usuários do tipo Editor se estão no mesmo grupo das Unidades atribuídas ao Eventos.

Validar lista de emails de Editores

---

wp-content/themes/tema-ceus/functions.php

Inclusão de condicional ao aplicar a query de consulta dos Eventos (Grandes Eventos e Eventos em Série) no admin do Portal dos CEUs

Condicional para a query de consulta

---

_git_plugins/grupo-editores/grupo-editores.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptAgendaDreBt.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptAgendaDreCl.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptAgendaDreCs.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptAgendaDreGn.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptAgendaDreIp.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptAgendaDreIt.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptAgendaDreJt.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptAgendaDrePe.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptAgendaDrePi.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptAgendaDreSa.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptAgendaDreSma.php
wp-content/themes/sme-portal-institucional/classes/Cpt/CptAgendaDreSmi.php
wp-content/themes/sme-portal-institucional/classes/LoadDependences.php
wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/ArchiveAgendaDre/ArchiveAgendaAjaxCalendarioDre.php
wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/ArchiveAgendaDre/ArchiveAgendaDre.php
wp-content/themes/sme-portal-institucional/classes/Usuarios/Dre/Dre.php
wp-content/themes/sme-portal-institucional/classes/assets/css/construtor.css
wp-content/themes/sme-portal-institucional/classes/assets/js/ajax-agenda-dre.js
wp-content/themes/sme-portal-institucional/classes/init.php
wp-content/themes/sme-portal-institucional/construtor/construtor-agenda_dres.php
wp-content/themes/sme-portal-institucional/construtor/construtor-editor_3_1b.php
wp-content/themes/sme-portal-institucional/construtor/construtor-mapa.php
wp-content/themes/sme-portal-institucional/construtor/construtor-noticias_destaque_dre.php
wp-content/themes/sme-portal-institucional/construtor/construtor-outras_noticias.php
wp-content/themes/sme-portal-institucional/construtor/construtor-outras_noticias_1_1.php
wp-content/themes/sme-portal-institucional/functions.php

- Criação de elementos novos no Construtor de Páginas
- Criação do calendário para cada DRE
- Criação do tipo de usuário DRE
- Permissionamento de acesso para usuários do tipo DRE

Migracao DRE multisite para o Portal

---

wp-content/themes/sme-portal-institucional/classes/Lib/Util.php
wp-content/themes/sme-portal-institucional/construtor/construtor-editor_1_1.php
wp-content/themes/sme-portal-institucional/construtor/construtor-editor_1_2.php
wp-content/themes/sme-portal-institucional/construtor/construtor-editor_1_3b.php
wp-content/themes/sme-portal-institucional/construtor/construtor-editor_1b_3.php
wp-content/themes/sme-portal-institucional/construtor/construtor-editor_2_2.php
wp-content/themes/sme-portal-institucional/construtor/construtor-editor_3_1.php
wp-content/themes/sme-portal-institucional/construtor/construtor-editor_3_1b.php
wp-content/themes/sme-portal-institucional/construtor/construtor-editor_3_2.php
wp-content/themes/sme-portal-institucional/construtor/construtor-editor_3_3.php
wp-content/themes/sme-portal-institucional/construtor/construtor-editor_3b_1.php
wp-content/themes/sme-portal-institucional/construtor/construtor-editor_4_1.php
wp-content/themes/sme-portal-institucional/construtor/construtor-editor_4_2.php
wp-content/themes/sme-portal-institucional/construtor/construtor-editor_4_3.php
wp-content/themes/sme-portal-institucional/construtor/construtor-editor_4_4.php
wp-content/themes/sme-portal-institucional/construtor/construtor-editor_fundo.php
wp-content/themes/sme-portal-institucional/construtor/construtor-editor_fundo_1_1.php
wp-content/themes/sme-portal-institucional/style.css

Imagens dentro de noticias e páginas com largura total do conteúdo

imagem com largura total dentro do conteudo

---

wp-content/themes/sme-visitas-monitoradas/classes/assets/css/home.css
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-newsletter_eventos.php

Inclusão do campo "Shortcode" para inserção do código de formulário integrado ao Mailchimp

Inclusao de shortcode com o form da newsletter

---

wp-content/themes/sme-visitas-monitoradas/classes/assets/css/home.css
wp-content/themes/sme-visitas-monitoradas/classes/assets/js/busca.js
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-banner_evento.php
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-bloco_de_busca.php
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-carousel_eventos.php
wp-content/themes/sme-visitas-monitoradas/footer.php
wp-content/themes/sme-visitas-monitoradas/functions.php
wp-content/themes/sme-visitas-monitoradas/header.php
wp-content/themes/sme-visitas-monitoradas/search.php

Pagina de resultados de busca com filtros e paginação

Pagina de resultados de busca

---

wp-content/themes/sme-portal-institucional/footer.php

Inclusão do selo Transparência e Boas Práticas de Gestão no rodapé do Portal.

Selo de transparencia no rodape

---

wp-content/themes/sme-portal-institucional/classes/Usuarios/Administrador/Administrador.php
wp-content/themes/sme-portal-institucional/classes/Usuarios/Colaborador/Colaborador.php
wp-content/themes/sme-portal-institucional/classes/Usuarios/Editor/Editor.php
wp-content/themes/sme-portal-institucional/classes/tutorial/tutorial.php
wp-content/themes/sme-portal-institucional/functions.php

- Retirar permissão de acesso a sessão "Tutoriais" no admin para usuários do tipo DRE
- Alterar a dica de preenchimento no cadastro de eventos das DREs

Permissoes para usuarios DRE

---

wp-content/themes/sme-visitas-monitoradas/classes/LoadDependences.php
wp-content/themes/sme-visitas-monitoradas/classes/ModelosDePaginas/Inscricoes/Inscricoes.php.php
wp-content/themes/sme-visitas-monitoradas/classes/TemplateHierarchy/LoopEvento/LoopEventoAgenda.php
wp-content/themes/sme-visitas-monitoradas/classes/TemplateHierarchy/LoopEvento/LoopEventoCabecalho.php
wp-content/themes/sme-visitas-monitoradas/classes/TemplateHierarchy/LoopEvento/LoopEventoPrincipal.php
wp-content/themes/sme-visitas-monitoradas/classes/assets/js/busca.js
wp-content/themes/sme-visitas-monitoradas/classes/assets/js/jquery.steps.js
wp-content/themes/sme-visitas-monitoradas/classes/init.php
wp-content/themes/sme-visitas-monitoradas/footer.php
wp-content/themes/sme-visitas-monitoradas/pagina-inscricoes.php
wp-content/themes/sme-visitas-monitoradas/style.css

Pagina de inscrições nos eventos e armazenamento no administrativo

Pagina de Inscricoes

---

_git_plugins/grupo-visitas/grupo-editores.php
wp-content/themes/sme-visitas-monitoradas/classes/Cpt/CptCadastroInscricoes.php
wp-content/themes/sme-visitas-monitoradas/classes/ModelosDePaginas/Inscricoes/Inscricoes.php.php
wp-content/themes/sme-visitas-monitoradas/classes/ModelosDePaginas/Login/LoginForm.php
wp-content/themes/sme-visitas-monitoradas/classes/assets/css/home.css
wp-content/themes/sme-visitas-monitoradas/classes/init.php
wp-content/themes/sme-visitas-monitoradas/construtor-layout.php
wp-content/themes/sme-visitas-monitoradas/footer.php
wp-content/themes/sme-visitas-monitoradas/functions.php
wp-content/themes/sme-visitas-monitoradas/header.php
wp-content/themes/sme-visitas-monitoradas/page.php
wp-content/themes/sme-visitas-monitoradas/single-evento.php
wp-content/themes/sme-visitas-monitoradas/single.php
wp-content/themes/sme-visitas-monitoradas/style.css
wp-content/themes/sme-visitas-monitoradas/tag.php

Visualização básica de inscrições nos eventos com filtros por Idade, DRE, Faixa Etária e Transporte.

Visualizacao basica de inscricoes

---

wp-content/themes/intranet/functions.php
wp-content/themes/intranet/header.php

Inclusão do campo "Analytics" nas configurações gerais do site e inclusão do código de acompanhamento no cabeçalho do site.

Campo Google Analytics

---

wp-content/themes/sme-visitas-monitoradas/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-visitas-monitoradas/classes/assets/css/home.css
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-card_destaque.php

Criação do elemento do Construtor "Card de destaque"

Card de destaque

---

wp-content/themes/sme-visitas-monitoradas/classes/Cpt/CptFaq.php
wp-content/themes/sme-visitas-monitoradas/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-visitas-monitoradas/classes/assets/css/construtor.css
wp-content/themes/sme-visitas-monitoradas/classes/init.php
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-faq.php
wp-content/themes/sme-visitas-monitoradas/functions.php

Criação do elemento "FAQ - Perguntas Frequentes" no Construtor de Páginas com opção de inclusão de vídeo e busca com filtro por título ou conteúdo.

Pagina perguntas frequentes

---

_git_plugins/create-user-without-send-email/create-user-without-send-email.php
_git_plugins/create-user-without-send-email/php/cuwp.php

Criação de novos usuários sem disparar o e-mail de ativação para usuários do tipo Admin dentro do Multisites

Criacao de usuarios por admin

---

_git_plugins/email-admin/email-admin.php

Envio de email para usuários do tipo Administrador em caso de novas páginas criadas por usuários do tipo Colaborador

Envio de email para o admin

---

wp-content/themes/sme-portal-institucional/classes/assets/css/pagina-inicial.css

Ajuste de grid para inclusão do embed do Acervo dentro do elemento de Abas do Construtor de páginas.

Ajuste de grid para embed do acervo

---

_git_plugins/coressovisitasapi/coressovisitasapi.php

Alteração na integração de login como CoreSSO para inclusão do novo endpoint com informações dos usuários

integracao com o endpoint do visitas monitoradas

---

wp-content/themes/tema-ceus/functions.php

Liberação de edição das Unidades que pertençam ao grupo atribuído ao usuário dentro da sessão Sobre o CEU para usuários do tipo Editor

Edicao sobre o CEU para usuarios do tipo Editor

---

wp-content/themes/sme-portal-institucional/construtor/construtor-mapa.php

Carregamento de mais de um mapa no elemento "Mapa" do Construtor de Páginas

Exibicao de mais de um mapa na pagina

---

wp-content/themes/sme-portal-institucional/classes/Cpt/CptAgendaSecretarioNew.php
wp-content/themes/sme-portal-institucional/classes/Usuarios/Colaborador/Colaborador.php
wp-content/themes/sme-portal-institucional/classes/init.php

- Remoção do modelo antigo da Agenda do Secretário
- Alteração do item "Nova Agenda do Secretário" para "Agenda do Secretário"

Remover modelo antigo da Agenda

---

wp-content/themes/sme-visitas-monitoradas/classes/ModelosDePaginas/Inscricoes/Inscricoes.php.php
wp-content/themes/sme-visitas-monitoradas/classes/TemplateHierarchy/LoopEvento/LoopEventoAgenda.php
wp-content/themes/sme-visitas-monitoradas/classes/TemplateHierarchy/LoopEvento/LoopEventoRelacionados.php
wp-content/themes/sme-visitas-monitoradas/classes/Usuarios/CamposAdicionais.php
wp-content/themes/sme-visitas-monitoradas/classes/assets/css/home.css
wp-content/themes/sme-visitas-monitoradas/classes/assets/js/ajax-agenda-secretario.js
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-banner_evento.php
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-carousel_eventos.php
wp-content/themes/sme-visitas-monitoradas/functions.php
wp-content/themes/sme-visitas-monitoradas/search.php

- Exibição dos meses disponíveis no lugar do mês correndo na agenda do evento
- Correção da exibição de datas repetidas nos eventos
- Remover informações de transporte no cadastro de eventos que forem na própria unidade
- Exibir a DRE de usuários do tipo assinante no Painel Administrativo

Melhorias apontadas pela rede

---

wp-content/themes/sme-visitas-monitoradas/classes/assets/js/busca.js
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-bloco_de_busca.php
wp-content/themes/sme-visitas-monitoradas/search.php

Inclusão do filtro "Tipo de Evento" na busca avançada

Inclusao de filtro de busca

---

wp-content/themes/sme-visitas-monitoradas/classes/ModelosDePaginas/Inscricoes/Inscricoes.php.php
wp-content/themes/sme-visitas-monitoradas/footer.php
wp-content/themes/sme-visitas-monitoradas/functions.php

- Reservar dia e horário após inscrições no eventos
- Liberar dia e horário após o usuário Administrador ou Editor modificar a inscrição para o status "Inscrição negada"

Reservar e liberar vagas para o evento

---

_git_plugins/email-admin/email-admin.php
wp-content/themes/sme-portal-institucional/classes/Usuarios/Dre/Dre.php
wp-content/themes/sme-portal-institucional/classes/Usuarios/EnviarParaRevisao.php
wp-content/themes/sme-portal-institucional/functions.php

- Permissão de publicação de eventos das agendas para usuários DRE
- Definição de categoria padrão para usuários do tipo DRE baseado em seu grupo

Permissoes de acesso e disparo de notificacoes

---

wp-content/themes/sme-portal-institucional/functions.php

Permissão para atribuir categorias em mídias para usuários do tipo DRE

Exibicao de categorias para midias

---

wp-content/themes/sme-portal-institucional/header.php
wp-content/themes/sme-portal-institucional/style.css

Exibição do titulo da página no cabeçalho da página inicial

Titulo da pagina inicial

---

wp-content/themes/sme-visitas-monitoradas/css/admin.css
wp-content/themes/sme-visitas-monitoradas/export-inscricoes.php.php
wp-content/themes/sme-visitas-monitoradas/functions.php

Exportações do relatório de inscrições do eventos em formato de Excel

Relatorio de inscricoes

---

wp-content/themes/sme-visitas-monitoradas/construtor/construtor-bloco_de_busca.php
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-carousel_eventos.php
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-newsletter_eventos.php
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-parceiros_do_projeto.php
wp-content/themes/sme-visitas-monitoradas/footer.php
wp-content/themes/sme-visitas-monitoradas/header.php

Inclusão dos tamanhos de imagem e ícones no topo, rodapé e elementos do Construtor de Páginas

melhorias de performance pagespeed

---

wp-content/themes/sme-portal-institucional/classes/Usuarios/Dre/Dre.php
wp-content/themes/sme-portal-institucional/functions.php

Limitar acesso a sessão "Cadastro de concursos" para usuários não admin que não estejam atribuídos a algum grupo que tenha permissão de acesso

limitar acesso ao cadastro de concursos

---

_git_plugins/grupo-visitas/grupo-editores.php
wp-content/themes/sme-visitas-monitoradas/classes/Cpt/CptCadastroInscricoes.php
wp-content/themes/sme-visitas-monitoradas/classes/ModelosDePaginas/Inscricoes/Inscricoes.php
wp-content/themes/sme-visitas-monitoradas/classes/Usuarios/Editor/Editor.php
wp-content/themes/sme-visitas-monitoradas/export-grupos.php
wp-content/themes/sme-visitas-monitoradas/functions.php
wp-content/themes/sme-visitas-monitoradas/js/wp-admin.js

- Inclusão dos campos "Total de Onibus" e "Onibus disponíveis"
- Limitar a visualização dos grupos para usuários do tipo Editor
- Exportar Grupos com as informações de Ônibus disponíveis

Quantidade de onibus por grupos

---

_git_plugins/grupo-visitas/grupo-editores.php
wp-content/themes/sme-visitas-monitoradas/classes/Cpt/CptCadastroTransporte.php
wp-content/themes/sme-visitas-monitoradas/classes/init.php

- Criação da sessão "Transporte" para cadastramento das empresas de transporte
- Permissionamento de acesso para todos os usuários na sessão "Transporte"

Cadastro de empresas de transporte

---

wp-content/themes/sme-visitas-monitoradas/classes/ModelosDePaginas/Inscricoes/Inscricoes.php
wp-content/themes/sme-visitas-monitoradas/css/admin.css
wp-content/themes/sme-visitas-monitoradas/functions.php

- Salvar informações do formulário de inscrição nos campos duplicados no admin
- Atualizar os campos duplicados caso os primeiros campos sejam modificados

Salvar campos duplicados nas abas

---

wp-content/themes/sme-visitas-monitoradas/classes/ModelosDePaginas/Inscricoes/Inscricoes.php
wp-content/themes/sme-visitas-monitoradas/css/admin.css
wp-content/themes/sme-visitas-monitoradas/functions.php

- Duplicar campos do Nome do Responsável na aba Inscrições
- Duplicar informações do campo "Nome do Responsável" caso seja modificado

Duplicar informacoes das incricoes nas abas

---

wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoBusca.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesTabs.php
wp-content/themes/tema-ceus/search.php

- Ordenação dos filtros por unidade baseado no titulo (ordem alfabética)
- Remoção do complemento do título na listagem das unidades nos filtros

Ordenacao e limitacao de titulo

---

wp-content/themes/acervodigital/construtor.php
wp-content/themes/acervodigital/search.php
wp-content/themes/acervodigital/searchform.php
wp-content/themes/acervodigital/single-acervo.php
wp-content/themes/sme-portal-institucional/search.php
wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoBusca.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesTabs.php
wp-content/themes/tema-ceus/search.php

Alterar o ID para slug nos filtros de buscas para que seja gravado no Google Analytics em categorias de filtros

Alterar id para slug nos filtros de busca

---

wp-content/themes/intranet/header.php

Alterar a ordem do titulo no cabeçalho da página pra "NOME DO SITE - TITULO DA PAGINA"

Alterar a ordem do titulo no cabecalho da pagina

---

wp-content/themes/intranet/classes/assets/css/construtor.css

Alteração das sessões Portais, Cursos e Recados para que tenham a mesma altura no conteúdo quando colocadas em colunas na mesma linha

Sessoes com o mesmo tamanho na altura

---

wp-content/themes/intranet/construtor/construtor-faq_1_1.php

Incluir a formatação do texto na saida de conteúdo das perguntas do FAQ

Incluir formatacao na saida de textos do FAQ

---

wp-content/themes/intranet/classes/TemplateHierarchy/ArchiveAgendaNew/ArchiveAgendaAjaxCalendarioNew.php
wp-content/themes/intranet/construtor/construtor-calendario_1_1.php

- Incluir todas as datas para eventos do tipo periodico no marcador do calendario
- Filtrar eventos baseado pela data selecionada dentro de um periodo dos eventos

Incluir eventos por periodo

---

wp-content/themes/sme-visitas-monitoradas/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-visitas-monitoradas/classes/TemplateHierarchy/LoopEvento/LoopEventoCabecalho.php
wp-content/themes/sme-visitas-monitoradas/classes/TemplateHierarchy/LoopEvento/LoopEventoPrincipal.php
wp-content/themes/sme-visitas-monitoradas/classes/assets/css/busca.css
wp-content/themes/sme-visitas-monitoradas/classes/assets/css/construtor.css
wp-content/themes/sme-visitas-monitoradas/classes/assets/css/home.css
wp-content/themes/sme-visitas-monitoradas/classes/assets/js/busca.js
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-bloco_de_busca.php
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-newsletter_eventos.php
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-parceiros_do_projeto.php
wp-content/themes/sme-visitas-monitoradas/header.php
wp-content/themes/sme-visitas-monitoradas/search.php
wp-content/themes/sme-visitas-monitoradas/style.css

Melhorias identificadas após analise se UI/UX para a versão mobile do site

Melhorias na versao mobile

---

wp-content/themes/sme-visitas-monitoradas/classes/assets/css/construtor.css
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-video_1_1.php

- Estilo do formulário na página Quem somos
- Alteração do elemento do Construtor de Páginas "Vídeo" para inserção de tamanho de largura dos vídeos

Estilo do formulario e tamanho do video

---

wp-content/themes/sme-visitas-monitoradas/classes/Cpt/CptCadastroParceiros.php
wp-content/themes/sme-visitas-monitoradas/classes/TemplateHierarchy/LoopEvento/LoopEventoParceiro.php
wp-content/themes/sme-visitas-monitoradas/classes/TemplateHierarchy/LoopParceiro/LoopParceiro.php
wp-content/themes/sme-visitas-monitoradas/classes/TemplateHierarchy/LoopParceiro/LoopParceiroCabecalho.php
wp-content/themes/sme-visitas-monitoradas/classes/TemplateHierarchy/LoopParceiro/LoopParceiroCta.php
wp-content/themes/sme-visitas-monitoradas/classes/TemplateHierarchy/LoopParceiro/LoopParceiroRelacionados.php
wp-content/themes/sme-visitas-monitoradas/classes/init.php
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-parceiros_do_projeto.php
wp-content/themes/sme-visitas-monitoradas/single-parceiros.php
wp-content/themes/sme-visitas-monitoradas/style.css

Pagina de detalhamento das informações do parceiro

Pagina de detalhe dos parceiros

---

wp-content/themes/sme-portal-institucional/classes/Cpt/CptPages.php

Selecionar grupo atribuído a página na listagem de páginas

Exibir grupo atribuido a pagina na listagem de paginas

---

wp-content/themes/intranet/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/intranet/classes/assets/css/construtor.css
wp-content/themes/intranet/construtor/construtor-card_imagem.php
wp-content/themes/intranet/construtor/construtor-certificados_1_1.php
wp-content/themes/intranet/style.css

- Criação do elemento do Construtor "Meus Certificados" para exibição dos certificados baseado no RF do usuário logado
- Criação do elemento do Construtor "Card com Imagem" para exibição de cards com imagem, titulo e URL.

Elemento do Construtor Meus Certificados

---

wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/ArchiveAgenda/ArchiveAgendaGetDatasEventos.php
wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/ArchiveAgendaDre/ArchiveAgendaAjaxCalendarioDre.php
wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/ArchiveAgendaNew/ArchiveAgendaAjaxCalendarioNew.php
wp-content/themes/sme-portal-institucional/construtor/construtor-agenda_dres.php
wp-content/themes/sme-portal-institucional/functions.php

Inclusão da possibilidade de eventos por período no calendário das DREs e Agenda do Secretário

Eventos unicos e por periodo

---

wp-content/themes/sme-portal-institucional/functions.php

Buscar os conteúdos do Acervo baseado no ID ou _Slug_(url) da categoria para incorporar o conteúdo dentro das páginas no Portal

Buscar conteudos filtrados por ID ou slug de categoria

---

wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/ArchiveAgenda/ArchiveAgendaAjaxCalendarioNew.php

Separação das consultas das datas do calendário do tipo Única e Periódica

Consulta de datas unicas e por periodo

---

wp-content/themes/sme-visitas-monitoradas/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-visitas-monitoradas/classes/TemplateHierarchy/LoopParceiro/LoopParceiroCabecalho.php
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-car_parceiros.php
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-form_parceiro.php
wp-content/themes/sme-visitas-monitoradas/footer.php
wp-content/themes/sme-visitas-monitoradas/functions.php
wp-content/themes/sme-visitas-monitoradas/style.css

Criação de dois novos elementos do Construtor de Páginas:
- Formulário de Inscrição
- Carrossel com o logo dos parceiros

Carrossel e formulario de parceiros

---

wp-content/themes/intranet/classes/Cpt/CptSmeExplica.php
wp-content/themes/intranet/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/intranet/classes/assets/css/construtor.css
wp-content/themes/intranet/classes/init.php
wp-content/themes/intranet/construtor/construtor-sme_explica.php
wp-content/themes/intranet/functions.php
wp-content/themes/intranet/js/post-like.js.js

- Listagem de informativos
- Filtro de busca por termo, categoria e data/período
- Botão de "curtida" na publicação

Listam de informativos e botao de curtida

---

wp-content/themes/intranet/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/intranet/classes/assets/css/construtor.css
wp-content/themes/intranet/classes/assets/css/pagina-inicial.css
wp-content/themes/intranet/construtor/construtor-sme_explica_dest.php

Criação do elemento do Construtor de Página "SME Explica - Destaques" com opção de exibição de vídeo internos e externos e opção de reprodução de áudio.

Elemento de destaques SME Explica

---

wp-content/themes/sme-visitas-monitoradas/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-feedback.php
wp-content/themes/sme-visitas-monitoradas/footer.php
wp-content/themes/sme-visitas-monitoradas/functions.php
wp-content/themes/sme-visitas-monitoradas/style.css

- Pagina de avalição de pós evento para as unidades escolares;
- Verificação e disparo de e-mail para o responsável pelas inscrições do evento avaliar o pós evento.

Pagina e email de avaliacao dos eventos

---

_git_plugins/coressoapi/coressoapi.php
wp-content/themes/intranet/construtor-layout.php
wp-content/themes/intranet/pagina-perfil.php
wp-content/themes/intranet/search.php

- Atualização do email no CoreSSO em caso de alteração do e-mail no perfil da Intranet
- Redirecionamento de usuários que não possuem e-mail cadastrado no CoreSSO para a pagina de perfil para que façam a atualização das informações.

Atualizar email no CoreSSO

---

wp-content/themes/sme-visitas-monitoradas/export-inscricoes.php.php
wp-content/themes/sme-visitas-monitoradas/functions.php

- Inclusão dos campos de avaliação do evento feito pela Unidade Escolar no relatório de inscrições;
- Alteração do filtro por DRE nos relatórios para que seja filtrado por grupo/DRE atribuido.

Incluir avaliacao da ue nos relatorios de inscricoes

---

_git_plugins/coressoapi/coressoapi.php
wp-content/themes/intranet/functions.php
wp-content/themes/intranet/includes/usuarios/cadastro_usuarios.php
wp-content/themes/intranet/includes/usuarios/src/SimpleXLSX.php
wp-content/themes/intranet/pagina-perfil.php

- Carregamento de usuários para o CoreSSO via arquivo xlsx;
- Validação de usuários de parceiras que estiverem sem e-mail exibindo o alerta e os levando para a página de perfil.

Carregamento de usuarios e validacao de email

---

wp-content/themes/sme-visitas-monitoradas/classes/Cpt/CptCadastroInscricoes.php
wp-content/themes/sme-visitas-monitoradas/classes/ModelosDePaginas/Inscricoes/Inscricoes.php
wp-content/themes/sme-visitas-monitoradas/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-visitas-monitoradas/classes/assets/css/construtor.css
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-minhas_inscricoes.php
wp-content/themes/sme-visitas-monitoradas/footer.php
wp-content/themes/sme-visitas-monitoradas/functions.php
wp-content/themes/sme-visitas-monitoradas/header.php
wp-content/themes/sme-visitas-monitoradas/style.css

Criação da página "Minhas inscrições" para o gerenciamento e visualização das inscrições feita pela Unidade Escolar (UE)

gerenciamento de agendamentos

---

wp-content/themes/intranet/classes/ModelosDePaginas/Login/LoginRecuperar.php
wp-content/themes/intranet/classes/assets/js/pagina-login.js
wp-content/themes/intranet/footer.php
wp-content/themes/intranet/functions.php

Alteração dos textos de alertas e textos de orientações na página de Recuperar Senha e Login

Alterar textos de alertas

---

_git_plugins/email-admin-visitas/email-admin.php

E-mail de confirmação de inscrição enviado para o parceiro com as informação da inscrição.

Email inscricao aprovada para parceiros

---

wp-content/themes/sme-visitas-monitoradas/classes/ModelosDePaginas/Inscricoes/Inscricoes.php
wp-content/themes/sme-visitas-monitoradas/classes/Usuarios/Parceiro/Parceiro.php
wp-content/themes/sme-visitas-monitoradas/classes/assets/css/construtor.css
wp-content/themes/sme-visitas-monitoradas/classes/init.php
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-minhas_inscricoes.php

Pagina de listagem e gerenciamento dos agendamentos para os eventos do parceiro

Gerenciamento dos agendamentos por parceiro

---

wp-content/themes/sme-visitas-monitoradas/classes/LoadDependences.php
wp-content/themes/sme-visitas-monitoradas/classes/ModelosDePaginas/Inscricoes/Inscricoes.php
wp-content/themes/sme-visitas-monitoradas/classes/assets/css/busca.css
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-bloco_de_busca.php
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-feedback.php
wp-content/themes/sme-visitas-monitoradas/construtor/construtor-parceiros_do_projeto.php
wp-content/themes/sme-visitas-monitoradas/footer.php
wp-content/themes/sme-visitas-monitoradas/search.php

- Alteração de ícone na busca
- Inclusão de carrossel de parceiros na home
- Inclusão de mascara de formatação nos campos de telefone
- Mensagem de confirmação de cancelamento na página de Feedback

melhorias identificadas primeiros usos

---

wp-content/themes/intranet/classes/ModelosDePaginas/Login/LoginRecuperar.php
wp-content/themes/intranet/footer-forms.php
wp-content/themes/intranet/footer.php
wp-content/themes/intranet/pagina-nova-senha.php

Criação da página "Redefinir nova senha" com validação de chave de autenticação e atualização de senha no CoreSSO

Pagina redefinir nova senha

---

wp-content/themes/intranet/functions.php
wp-content/themes/intranet/includes/usuarios/atualizar_usuarios.php

Atualização dos dados de e-mail dos usuários no CoreSSO via upload de planilha no admin da Intranet

Pagina de atualizacao de email dos usuarios

---

_git_plugins/coressoapi/coressoapi.php
wp-content/themes/intranet/classes/ModelosDePaginas/Login/LoginRecuperar.php
wp-content/themes/intranet/pagina-nova-senha.php

- Alteração do texto na página de recuperar a senha de "Rede Parceira" para "Unidades Parceiras";
- Correção da palavra "ultima" para "última" no alerta de senha;
- Alteração do endpoint para recebimento de dados do usuário logado.

Alteracoes de texto e dados de usuario

---

wp-content/themes/intranet/classes/Cpt/CptMuralProf.php
wp-content/themes/intranet/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/intranet/classes/assets/css/construtor.css
wp-content/themes/intranet/classes/init.php
wp-content/themes/intranet/construtor/construtor-mural_prof.php

Criação do elemento do Construtor de Páginas "Mural dos Professores" para a listagem das publicações dos professores com filtros por título, conteúdo e período.

Listagem das publicacoes dos Professores

---

wp-content/themes/intranet/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/intranet/classes/assets/css/construtor.css
wp-content/themes/intranet/construtor/construtor-banner_horiz.php

Criação do elemento do Construtor de Páginas "Banner Horizontal" com os seguintes campos:
- Titulo
- Subtítulo
- Descrição
- Imagem
- Link "Ver mais"

Secao mural dos professores

---

wp-content/themes/intranet/classes/Lib/SimpleXLSXGen.php
wp-content/themes/intranet/classes/init.php
wp-content/themes/intranet/export-users.php
wp-content/themes/intranet/pagina-perfil.php
wp-content/themes/intranet/style.css

- Inclusão dos campos de autorização de recebimento das novidades via e-mail e WhatsApp;
- Página de exportação de usuários com Nome, Email, Telefone, Cargo, DRE e usuários que autorizaram o recebimento de mensagens.

Autorizacao newsletter whatspp e exportacao de usuarios

---

wp-content/themes/acervodigital/functions.php
wp-content/themes/sme-visitas-monitoradas/header.php

Botão de login para usuários não logados no sistema no topo do cabeçalho.

Botao de login no menu superior

---

wp-content/themes/intranet/classes/wp_bootstrap_navwalker.php
wp-content/themes/intranet/header.php
wp-content/themes/intranet/style.css

Melhoria da exibição do submenu no menu principal do site na versão mobile.

Melhoria de exibicao do submenu mobile

---

wp-content/themes/intranet/includes/usuarios/atualizar_usuarios.php

Padronização da coluna de atualização de usuário para o uso de 3 colunas (Nome da Unidade, Código EOL, E-mail) para utilização no cadastro ou atualização de dados

Padronizar planilha de atuazacoes

---

wp-content/themes/tema-ceus/functions.php

Incluir o campo dia da semana do tipo repetidor (ACF) na classe Wp_query

Incluir campo dia da semana na classe wp_query

---

wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleRelacionadas.php
wp-content/themes/tema-ceus/style.css

- Incluir transparência no título do evento para atividades que fazem parte de um Grande Evento;
- Melhoria no filtro incluindo categoria principal e subcategorias no mesmo seletor.

Transparencia no titulo da atividade e melhoria no filtro

---

wp-content/themes/sme-portal-institucional/functions.php
wp-content/themes/sme-portal-institucional/style.css

Incluir a opção de download de múltiplos arquivos na incorporação do conteúdo de arquivos do Acervo Digital dentro do Portal de comunicação.

Acervo com multiplos arquivos

---

wp-content/themes/sme-portal-institucional/construtor-layout.php

Proteção por senha nos conteúdos para páginas que utilizam o modelo Construtor de Páginas

Construtor de paginas com opcao de protecao por senha

---

wp-content/themes/sme-portal-institucional/classes/Cpt/CptPages.php
wp-content/themes/sme-portal-institucional/functions.php

- Inclusão de opção para limpeza de conteúdo nas ações em massa na listagem de páginas;
- Inclusão da coluna Modelo de Página na listagem de páginas;
- Inclusão de filtro por modelo de página na listagem de páginas;

Remover conteudo em massa de paginas

---

wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoSlide.php
wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesSlide.php
wp-content/themes/tema-ceus/search.php

Ocultar o seletor de slide quando não houver eventos em destaque

Ocultar seletor de slide quando vazio

---

wp-content/themes/sme-portal-institucional/functions.php

Exibição da capa inserida manualmente no Acervo Digital em caso de incorporação de conteúdo no Portal de Comunicação

Exibir capa selecionada manualmente no Acervo Digital

---

wp-content/themes/acervodigital/export-users.php
wp-content/themes/sme-portal-institucional/export-users.php
wp-content/themes/tema-ceus/export-users.php

Incluir a coluna Nome nos relatórios de exportação de usuários do Portal de Educação, Acervo Digital e Portal do CEUs

Incluir coluna Nome no excel de exportacao

---

wp-content/themes/acervodigital/single-acervo.php

Exibição dos campos Qt de Páginas, Edição/Volume e Categorias na aba Especificações

Exibir os campos Qt Pagina Edicao e Categorias

---

_git_plugins/coressoapi/coressoapi.php

Em caso de usuários que tiverem o e-mail atualizado direto no CoreSSO verificar se ele não foi cadastrado no WordPress com um e-mail temporário, caso esteja com o e-mail temporário o mesmo será atualizado no WordPress.

Verificar se o usuario utiliza um email temporario

---

wp-content/themes/tema-conselhos/classes/Lib/SimpleXLSXGen.php
wp-content/themes/tema-conselhos/classes/init.php
wp-content/themes/tema-conselhos/export-users.php
wp-content/themes/tema-conselhos/functions.php

Incluir a opção "Exportar Usuários" no menu Usuários para o tema utilizado nos portais do Conselhos

Exportar usuarios dos Conselhos

---

wp-content/themes/acervodigital/functions.php
wp-content/themes/acervodigital/single-acervo.php

Incluir o contador de visualizações baseado no clique do botão "Visualizar" do Acervo com atualização das visualizações via Ajax

Contador de visualizacoes do Acervo

---

wp-content/themes/tema-ceus/functions.php

Campos de datas obrigatórios em caso de Tipo de Evento selecionado a opção Grande evento e Tipo de data selecionado como Período

Campos de datas obrigatorios para grandes eventos

---

wp-content/themes/sme-visitas-monitoradas/classes/TemplateHierarchy/LoopEvento/LoopEventoPrincipal.php

Exibição correta da formatação dos textos em "Sobre este evento"

Exibir formatacao correta dos textos

---

_git_plugins/email-admin-visitas/email-admin.php

Inclusão dos campos abaixo no e-mail enviado aos parceiros com a confirmação da visita:
- Nome da UE;
- Nome do responsável pela visita;
- Faixa etária do grupo;
- Telefone de contato do responsável;
- E-mail do responsável;
- Se no grupo tem estudantes PCD ou com mobilidade reduzida.

Informacoes adicionais no email de aprovacao para parceiros

---

wp-content/themes/intranet/classes/ModelosDePaginas/Login/LoginRecuperar.php

Alterar os textos na página "Esqueceu sua senha" para receber os valores diretamente do admin

Receber titulo e texto do editor da pagina no admin

---

wp-content/themes/acervodigital/functions.php
wp-content/themes/acervodigital/search.php
wp-content/themes/acervodigital/single-acervo.php

Inclusão e exibição do contador de downloads em cada publicação do Acervo Digital

Contador de downloads do Acervo

---

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
wp-content/themes/sme-portal-institucional/construtor/construtor-acervo_embed.php
wp-content/themes/sme-portal-institucional/functions.php

Novo elemento do Construtor de Páginas "Acervo", criado para fazer a incorporação do conteúdo de um acervo digital dentro do conteúdo do Portal de Comunicação.

Acervo novo elemento do Construtor de Paginas

---

wp-content/themes/sme-portal-institucional/classes/tutorial/tutorial.php

Permissão de visualização de tutoriais por tipo de função/perfil do usuário logado no painel administrativo

Exibir tutoriais por tipo de perfil/funcao
