wp-content/themes/sme-portal-institucional/classes/LoadDependences.php
Existia uma requisição de css do front que estava sendo aplicado no admin, Agora o CSS está somente para o front e o mesmo não atrapalha no admin
=> Foi adicionado criterios no css para correção do bug

wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/Tag.php
Ajuste no looping de notícias baseado nas tags alterando a busca de nome da tag para o id da tag
=> Ajuste no looping das tags

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/PaginaInicial/PaginaInicial.php, wp-content/themes/sme-portal-institucional/footer.php, wp-content/themes/sme-portal-institucional/header.php, wp-content/themes/sme-portal-institucional/search.php
Ocultar os ícones das redes sociais do topo e do rodapé quando estiverem vazio no painel administrativo do site.
=> Ocultar redes sociais do topo e rodape

_git_plugins/bulk-remove-posts-from-category/css/wpbulkremove_style.css, _git_plugins/bulk-remove-posts-from-category/js/wpbulkremove.js, _git_plugins/bulk-remove-posts-from-category/license.txt, _git_plugins/bulk-remove-posts-from-category/readme.txt, _git_plugins/bulk-remove-posts-from-category/wpbulkremove.php
Opção para remover as notícias de uma ou mais categorias durante a edição em massa.
Correção do parâmetro _post_type_ no editor em massa.
=> Remover categorias na edicao em massa

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php, wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/PaginaMaisNoticias/PaginaMaisNoticiasDestaques.php, wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/PaginaMaisNoticias/PaginaMaisNoticiasOutrasNoticias.php, wp-content/themes/sme-portal-institucional/classes/TemplateHierarchy/LoopSingle/LoopSingleRelacionadas.php, wp-content/themes/sme-portal-institucional/functions.php
- Padronização de tamanho das imagens destacadas das noticias;
- Se não houver imagem destacada será pego a primeira imagem dentro da publicação;
- Não tendo nenhuma das duas imagens acima será inserido uma imagem padrão com logo da prefeitura.
=> Padrao para imagens destacadas

wp-content/themes/tema-ceus/classes/Breadcrumb/Breadcrumb.php, wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoBusca.php, wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoEventos.php, wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaProgramacao/PaginaProgramacaoSlide.php, wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaUnidades/PaginaUnidadesMapa.php, wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleCabecalho.php, wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleNoticiaPrincipal.php, wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopSingle/LoopSingleRelacionadas.php, wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesSlide.php, wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesTabs.php, wp-content/themes/tema-ceus/search.php, wp-content/themes/tema-ceus/style.css
- Inclusão da opção "Toda a rede" para eventos que são oferecidos por COCEU;
- Inclusão da opção "Online" para eventos que são online;
- Alteração na página de cada CEU para trazer além dos eventos do próprio CEU também trazer os eventos que são de toda a rede.
- Alteração na página individual do evento, slides e listagem de eventos para remover o link que leva para a unidade pertencente nos casos dos eventos que são para toda a rede;
- Alteração no _Breadcrumb_ para mostrar a unidade no lugar da categoria.
=> Alteracao cadastro de eventos

wp-admin/edit-form-advanced.php, wp-admin/includes/meta-boxes.php, wp-includes/post.php
- Ajuste de bug no Core do WordPress para que os links permanentes não sejam alterados após a publicação ser enviada para revisão por usuários do tipo Colaborador.
=> Adicionando link permanente para colaboradores ao enviar para revisao

wp-content/themes/sme-portal-institucional/classes/Usuarios/Colaborador/Colaborador.php
Os seguintes itens foram ocultados do menu para colaboradores:
- Opções Gerais
- Notícias
- Agenda do Secretário
- Organograma
- Aparência
- Configurações
=> Ocultar itens do menu para colaboradores

wp-content/themes/sme-portal-institucional/classes/Cpt/CptPosts.php, wp-content/themes/sme-portal-institucional/functions.php
- Definir para notícias que não possuem imagem destacada uma imagem padrão;
- Exibir as imagens destacadas na listagem de noticias
=> Definir imagem de destaque padrão nas noticias

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/PaginaImagemVideo/PaginaImagemVideo.php, wp-content/themes/sme-portal-institucional/footer.php
Alteração para regra de validação de links excluindo itens de ação como seta do slide, botões de abas e acordeons e links de telefone e email.
=> Validacao para links de componentes

_git_plugins/email-admin-ceu/email-admin-ceu.php, wp-content/themes/tema-ceus/functions.php
- Não disparar emails para administradores em caso de utilização da funcionalidade "Visualizar" dos eventos
- Permitir que colabores utilizem a função "Visualizar" nos eventos
=> Nao disparar email em caso de preview das noticias

wp-content/themes/tema-ceus/classes/Cpt/CptPosts.php, wp-content/themes/tema-ceus/functions.php
Armazenar os campos personalizado Localização,  Tipo de Evento, Inscrições e Descrição em caso de Salvamento Automático feito pelo WordPress.
=> Salvar campos personalizados durante o salvamento automatico

wp-content/themes/sme-portal-institucional/classes/assets/css/mapa-dres.css
Ajuste de conflito no elemento de Cards do Boostrap que ocorreu dentro dos Cards no Mapa das DREs na versão mobile.
=> Ajustar exibicao das informacoes nos cards do mapa na versao mobile

wp-content/themes/sme-portal-institucional/functions.php
Alterar dica de preenchimento no cadastro/edição de evento na Agenda do Secretário no painel administrativo.
=> Dica de preenchimento agenda do secretario

wp-content/themes/sme-portal-institucional/classes/ModelosDePaginas/Layout/construtor.php
Ao abrir a o elemento "Sanfona" do Construtor de Página a rolagem da página seja levada para o conteúdo da Sanfona abrindo no topo do navegador.
=> Abrir conteudo da sanfona no topo da pagina

wp-content/themes/tema-ceus/functions.php
Ocultar a opção "Evento Principal" dentro de "Grande Evento" no cadastro de eventos do CEUs para usuários não administradores
=> ocultar grande eventos para nao admins

_poc/tema-ceus/functions.php
Incluir a possibilidade de usuários do tipo Editor fazerem a gestão de usuários do tipo Colaborador e Editor que estejam no mesmo grupo.
=> Gestao de usuarios por grupos de DREs

wp-content/themes/sme-portal-institucional/construtor/construtor-noticias_destaque_dre.php, wp-content/themes/sme-portal-institucional/functions.php
Alteração no elemento do Construtor de Páginas "Noticias de destaque - DRE" incluindo a possibilidade de selecionar as noticias por categoria ou por seleção manual e incluindo filtro de notícias para usuários do tipo DRE baseado nas categorias liberadas para o seu grupo.
=> Escolher noticias em destaque

wp-content/themes/tema-ceus/css/admin.css, wp-content/themes/tema-ceus/functions.php
- Ocultar campos no cadastro de usuários
- Limitar o seletor de grupos para o cadastro de novos usuários
- Ocultar o contador de usuários por tipo
=> Gerenciamento de usuarios por grupo para editores

wp-content/themes/intranet/header.php
Remover o link para o painel administrativo no menu de acesso rápido para usuários do tipo administrador
=> remover link do painel para usuarios do tipo admin

wp-content/themes/tema-ceus/functions.php
Permitir salvamento de formatação de texto na funcionalidade de auto salvamento do WordPress para o campo personalizado "Descrição" utilizado no cadastro das unidades dos CEUs
=> Manter formatacao de texto no auto salvamento para campos personalizados

wp-content/themes/sme-portal-institucional/search.php
- Modificar filtro "Filtre por tipo de conteúdo" removendo todas as opções de páginas das DRE
- Modificar filtro "Filtre por site" removendo das opções todos os sites das DREs
- Modificar a busca de conteúdo filtrado por Noticias das DREs retirando a opção de site (Multisites) e incluindo o filtro pro Categoria dentro do Portal de Educação.
=> Remover DREs da busca de conteudo

wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidades.php
Remoção da linha (row) do Bootstrap na página de unidades para não deslocar as colunas quando aplicado a diminuição do zoom no navegador
=> remover linha do bootstrap para nao quebrar colunas no zoom

wp-content/themes/intranet/pagina-perfil.php
Remover da Biblioteca de mídia as imagens que foram substituídas na página de perfil dos usuários
=> Remover imagem anterior de perfil da biblioteca do WP

wp-content/themes/tema-ceus/classes/TemplateHierarchy/LoopUnidades/LoopUnidadesTabs.php
Exibir a foto principal da aba "Sobre a Unidade" caso esteja definido apenas a Foto Principal no cadastro dentro do admin
=> Exibir foto principal na aba Sobre a Unidade

wp-content/themes/tema-ceus/404.php, wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaUnidades/PaginaUnidades.php, wp-content/themes/tema-ceus/classes/ModelosDePaginas/PaginaUnidades/PaginaUnidadesMapa.php, wp-content/themes/tema-ceus/footer.php, wp-content/themes/tema-ceus/functions.php
- Na página de Unidade e Mapa de Unidades exibir os CEUs que estão com status de revisão pendente;
- Redirecionar os usuários caso a unidade esteja como pendente para uma página de aviso sobre a manutenção do conteúdo da unidade.
=> Exibir CEUs em revisao pendente e redicionar para manutencao

wp-content/themes/sme-portal-institucional/classes/Usuarios/Dre/Dre.php, wp-content/themes/sme-portal-institucional/functions.php
Ocultar filtros de submenu nas listagem de notícias e páginas mantendo apenas os conteúdos ligados ao grupo do usuário DRE
=> Restringir noticias e paginas para usuarios DREs

wp-content/themes/sme-portal-institucional/functions.php
Filtrar os grupos listados no seletor de grupo ao criar uma página para exibir somente os grupos atribuídos aos usuários não administradores
=> Filtrar os grupos atribuidos ao usuario no seletor de grupos

wp-content/themes/sme-portal-institucional/functions.php
- Filtrar a lista de contato pelos contatos atribuído ao grupo do qual o usuário faz parte;
- Ocultar os filtros de publicados, rascunhos, pendente, lixeira para usuários não administradores;
- Filtrar a atribuição de grupos no cadastro de contatos para os grupos no qual o usuário faz parte.
=> Filtrar contatos por grupo atribuido ao usuario
